lerna.json, package.json, packages/subgraph/package.json, yarn.lock
Lerna was only used in the subgraph package to execute the compile command of the contracts package. But a simple ``cd ../contracts && yarn compile`` is doing his job as well.
=> Removes lerna dependency used in the subgraph package

packages/contracts/CHANGELOG.md, packages/contracts/contracts/factory/DAOFactory.sol, packages/contracts/test/dao-factory.ts
The following PR brings the `VoteConfig` struct in order to make easier for sdk to include typechain support.
There're some things that would need a little bit of thought.
1. We could bring `VoteConfig` struct in the `MajorityVoting`, but due to the nature of not being able to do inheritance on structs, it would be really hard to upgrade WhitelistVoting contract if it needs one more variable in the config and for ERC20Voting, if the config should stay the same way. Hence, including this in MajorityVoting is kind of tricky.
2. Even if We do the above and assume that VoteConfig will always be the same for `WhitelistVoting` and `ERC20Voting`,  There's one more thing to keep in mind. Since it's a struct, new developers might come right away and decide to add one more variable into the struct, …
=> vote config with struct

packages/contracts/CHANGELOG.md, packages/contracts/contracts/core/DAO.sol, packages/contracts/contracts/core/IDAO.sol, packages/contracts/contracts/core/component/MetaTxComponent.sol, packages/contracts/contracts/test/DAOMock.sol, packages/contracts/test/core/dao.ts, packages/contracts/test/dao-factory.ts, packages/subgraph/CHANGELOG.md, packages/subgraph/manifest/subgraph.placeholder.yaml, packages/subgraph/src/dao/dao.ts, packages/subgraph/tests/dao/dao.test.ts, packages/subgraph/tests/dao/utils.ts
Task: [APP-290](https://aragonassociation.atlassian.net/browse/APP-290)
Similar to the `hasPermission()` functionality of the ACL, also other publicly visible methods, that make up the DAO (e.g. ERC1271) should be part of the `IDAO` interface to be used in `Component` and `MetaTxComponent`. 
Accordingly, `trustedForwarder()`, `isValidSignature()`, and other methods should be part of the `IDAO` interface to be used in `Component` and `MetaTxComponent` so that things are uniform.
If we want to redesign at a later point, this makes it easier.
=> Complete the IDAO interface

.github/workflows/npm-release-reusable.yml
- Fixes bug in `npm-release-reusable.yml` workflow which runs when it shouldn't
- Adds feature to write back the package.json of the packages `contracts` and `contracts-ethers` when a new version is published
=> Fix npm release and writeback deployed npm versions

.github/workflows/subgraph-deploy.yaml
Fix the `build-deploy` job in to run only when a `subgraph:*` label is set.
Task: [DOPS-322](https://aragonassociation.atlassian.net/browse/DOPS-322)
=> fix: build and deploy job for subgraph deployment

packages/subgraph/CHANGELOG.md, packages/subgraph/schema.graphql, packages/subgraph/src/dao/dao.ts, packages/subgraph/tests/dao/dao.test.ts
Previously Withdraws and Deposits were handles by different types and exposed as 2 different fields in the DAO.
These are now combines into 1 field (`transfers`)  and are differentiated by the field `type`.
Task: [APP-962](https://aragonassociation.atlassian.net/browse/APP-962)
=> fix: combines transfers into one type

packages/contracts/contracts/plugin/examples/count/CounterV2.sol, packages/contracts/contracts/test/plugin-mock/UUPSUpgradeable/PluginUUPSUpgradeableV2Mock.sol
This bug fix was found while working on task [APP-1077](https://aragonassociation.atlassian.net/browse/APP-1077) and prevents double-initialization of freshly installed plugins with `version > 1` that use setters for the initialization of storage variables.
This fix replaces the `initializer` modifier by the `reinitializer(uint8 version)` modifier for the `initialize` functions to prevent the setters to be called after `initialize` was executed.
Tests for this fix should be added together with [APP-1077](https://aragonassociation.atlassian.net/browse/APP-1077) to the `Counter` and `PluginUUPSUpgradeableMock` examples.
=> Fix to prevent double initialization of upgradeable plugins

.gitignore, packages/contracts/docs/core/03-reference-guide/index.md
An index file was missing in the docs folder because it was ignored `packages/contracts/docs/core/03-reference-guide/index.md`.
=> Added missing index file

packages/contracts/CHANGELOG.md, packages/contracts/contracts/factory/TokenFactory.sol, packages/contracts/contracts/tokens/GovernanceERC20.sol, packages/contracts/contracts/voting/erc20/ERC20VotingSetup.sol, packages/contracts/test/core/dao.ts, packages/contracts/test/factory/token-factory.ts, packages/contracts/test/merkle/merkle-minter.ts, packages/contracts/test/voting/allowlist-voting-setup.ts, packages/contracts/test/voting/erc20-voting-setup.ts
* Adds initialize mint possibility for GovernanceERC20's initialize. 
* Though, not for GovernanceWrappedERC20 as to do this, it's required for the mint addresses to have approved allowance for GovernanceWrappedERC20. This is problematic as most of the time, the addresses creator passes won't have allowance which will make the tx fail. **NOTE** that it's still possbile to mint on GovernanceWrappedERC20 without approval which would cause that amounts on the underlying token would still stay the same, but we would still mint on GovernanceWrappedERC20 ! this seems token duplication, but might be desirable. Haven't fully thought so will hear it from you first.
* Removes MerkleMinter Deployment from ERC20VotingSetup
=> add mint for tokens in the initialize.

.github/helpers/contracts/prepare.js, .github/helpers/subgraph/buildMatrix.js, .github/workflows/comment-triggers.yml, .github/workflows/contract-tests.yml, .github/workflows/contracts-deploy.yml, .github/workflows/create-dummy-dao.yml, .github/workflows/documentation-update.yml, .github/workflows/mythx-changed.yml, .github/workflows/mythx-full.yml, .github/workflows/npm-release-reusable.yml, .github/workflows/npm-release.yml, .github/workflows/subgraph-deploy.yaml, .github/workflows/subgraph-tests.yml
- Removes "set-output" echos from workflows. (https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
- Allows npm release workflow to run from all pull requests
Task: [ID]()
=> App 1232 core npm ethers doesnt export the updated active contracts list

packages/contracts/contracts/voting/majority/MajorityVotingBase.sol
In https://github.com/aragon/core/pull/141, it was written that we use 
$$\text{relative support} = N_\text{yes} / (N_\text{yes} + N_\text{no})$$
https://github.com/aragon/core/blob/c498623e06ac84ae1d948eba46038a7b7d38a46c/packages/contracts/contracts/voting/majority/MajorityVotingBase.sol#L17
but this was not changed in the respective line. https://github.com/aragon/core/blob/c498623e06ac84ae1d948eba46038a7b7d38a46c/packages/contracts/contracts/voting/majority/MajorityVotingBase.sol#L274
This PR fixes this mistake by removing `vote_.abstain`.
=> Fix wrong relative support calculation differing from the comments

packages/contracts/docs/core/01-how-it-works/01-the-core-contracts/02-permissions.md
This PR reflects the `PermissionManager` changes introduced in https://github.com/aragon/core/pull/131 in the docs.
Task: [APP-1201](https://aragonassociation.atlassian.net/browse/APP-1201)
=> Reflect the `PermissionManager` changes in the docs

packages/contracts/.env.example, packages/contracts/hardhat.config.ts
Let's be more aware of gas costs. 
Setting `REPORT_GAS` prints the gas report after `yarn test`.
Setting `COINMARKETCAP_API_KEY` with a Coinmarketcap API key prints the USD equivalent.
=> Adds gas reporting environment variables to the .env example

packages/subgraph/CHANGELOG.md, packages/subgraph/src/packages/addresslist/addresslist-voting.ts, packages/subgraph/src/packages/token/token-voting.ts, packages/subgraph/tests/addresslist-voting/addresslist-voting.test.ts, packages/subgraph/tests/token-voting/token-voting.test.ts
If a None vote gets emitted by either TokenVoting or AddresslistVoting the subgraph shouldn't store that vote, because it isn't actual any vote and thus it shouldn't influence the subgraph
Task: APP-1498
[APP-1498]: https://aragonassociation.atlassian.net/browse/APP-1498?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: don't store None votes in subgraph

packages/contracts/contracts/voting/token/TokenVotingSetup.sol
As far as I remember, we decided to remove merkle minter/distributor from token-voting-setup due to complexity and not bringing value. 
Not sure what the values are for merkle minter and merkle distributor now. Maybe we will design a plugin that will be called MerkleMinterAndDistributor plugin and will install this plugin ? Should it be even the plugin ? if not, how else can dao use it without installing ? 
Task: [ID]()
=> remove merkleminter/distributor from tokenvotingsetup

packages/contracts/contracts/plugin/PluginRepo.sol
Reducing types. I had uint256 previously in mappings to reduce costs ! as you know, handling `uint8` in one slot(while there's no other thing in there) costs more than handling `uint256`. but this might make the confusion that `Tag` is `uint8, uint16`, but in the mapping, we use `uint256` instead of `uint8/16`. Since the costs will not be increased too much, I think it might be better to remove the confusion. Thoughts ? If you agree, then, review ! if not, I got no problem leaving as it is too.
@mathewmeconry @brickpop 
Task: [ID]()
=> plugin repo types changes

packages/contracts/CHANGELOG.md, packages/contracts/docs/core/01-how-it-works/01-the-core-contracts/01-the-dao-contract.md, packages/contracts/docs/core/01-how-it-works/01-the-core-contracts/02-permissions.md, packages/contracts/docs/core/01-how-it-works/01-the-core-contracts/03-plugins.md, packages/contracts/docs/core/01-how-it-works/02-the-dao-framework/02-plugin-repository/04-plugin-setup.md, packages/contracts/src/core/dao/DAO.sol, packages/contracts/src/framework/dao/DAOFactory.sol, packages/contracts/test/core/dao/dao.ts, packages/contracts/test/framework/dao/dao-factory.ts
- removed `WITHDRAW_PERMISSION` that had remained on `DAO.sol` despite not being used
- added`REGISTER_STANDARD_CALLBACK_PERMISSION` in `DAOFactory` that was not granted
- added `SET_TRUSTED_FORWARDER_PERMISSION` to the list of restricted permissions in `function isPermissionRestrictedForAnyAddr` that was not present there
=> Removed the forgotten `WITHDRAW_PERMISSION` and other permission-related fixes

packages/contracts/CHANGELOG.md, packages/contracts/src/core/dao/DAO.sol, packages/contracts/src/core/permission/PermissionManager.sol, packages/contracts/src/core/plugin/dao-authorizable/DaoAuthorizable.sol, packages/contracts/src/core/plugin/dao-authorizable/DaoAuthorizableUpgradeable.sol, packages/contracts/src/core/utils/auth.sol, packages/contracts/src/framework/plugin/repo/PluginRepo.sol, packages/contracts/src/test/plugin/SharedPluginTest.sol, packages/contracts/test/core/dao/dao.ts, packages/contracts/test/core/permission/permission-manager.ts, packages/contracts/test/core/plugin/parameter-scoping-condition.ts, packages/contracts/test/core/plugin/shared-plugin.ts, packages/contracts/test/framework/dao/dao-registry.ts, packages/contracts/test/framework/plugin/plugin-repo-factory.ts, packages/contracts/test/framework/plugin/plugin-repo-registry.ts, packages/contracts/test/framework/plugin/plugin-repo.ts, packages/contracts/test/framework/plugin/plugin-setup-processor.ts, packages/contracts/test/framework/utils/ens/ens-subdomain-registry.ts, packages/contracts/test/framework/utils/interface-based-registry.ts, packages/contracts/test/plugins/governance/admin/admin.ts, packages/contracts/test/plugins/token/distribution/merkle-minter.ts, packages/contracts/test/test-utils/uups-upgradeable.ts, packages/contracts/test/token/erc20/governance-erc20.ts
Remove`PermissionManager` feature that allowed for having the `ROOT_PERMISSION_ID` permission for a specific `where` target contract and simplified `auth` in `PermissionManager` by always setting `where = address(this)`.
=> Remove `PermissionManager` feature

packages/contracts/CHANGELOG.md, packages/contracts/src/core/dao/DAO.sol, packages/contracts/src/core/plugin/PluginCloneable.sol, packages/contracts/src/core/plugin/PluginUUPSUpgradeable.sol, packages/contracts/src/plugins/counter-example/MultiplyHelper.sol, packages/contracts/src/plugins/counter-example/v1/CounterV1.sol, packages/contracts/src/plugins/counter-example/v2/CounterV2.sol, packages/contracts/src/plugins/governance/majority-voting/addresslist/AddresslistVoting.sol, packages/contracts/src/plugins/governance/majority-voting/token/TokenVoting.sol, packages/contracts/src/plugins/governance/multisig/Multisig.sol, packages/contracts/src/plugins/token/MerkleDistributor.sol, packages/contracts/src/plugins/token/MerkleMinter.sol, packages/contracts/src/test/plugin/AdminCloneFactory.sol, packages/contracts/test/core/plugin/parameter-scoping-condition.ts, packages/contracts/test/core/plugin/shared-plugin.ts, packages/contracts/test/plugins/governance/admin/admin.ts, packages/contracts/test/plugins/governance/majority-voting/majority-voting.ts
Best practice by OZ and auditor suggestions recommend to call  `_disableInitializers` for proxy contracts to not leave them uninitialized. 
This PR moves `_disableInitializers` inside `PluginCloneable` and `PluginUUPSUpgradeable` constructors so that people cannot accidentally forget.
After double-checking with OZ, nothing speaks against moving it into the parent constructor: https://forum.openzeppelin.com/t/putting-disableinitializers-in-a-parent-constructor/34771/3
=> Moves `_disableInitializers` inside `PluginCloneable` and `PluginUUPSUpgradeable`

packages/contracts/docs/templates/common.hbs, packages/contracts/src/core/dao/DAO.sol, packages/contracts/src/core/dao/IDAO.sol, packages/contracts/src/core/permission/PermissionManager.sol, packages/contracts/src/core/plugin/Plugin.sol, packages/contracts/src/core/plugin/PluginCloneable.sol, packages/contracts/src/core/plugin/PluginUUPSUpgradeable.sol, packages/contracts/src/core/plugin/dao-authorizable/DaoAuthorizable.sol, packages/contracts/src/core/plugin/dao-authorizable/DaoAuthorizableUpgradeable.sol, packages/contracts/src/core/plugin/proposal/Proposal.sol, packages/contracts/src/core/plugin/proposal/ProposalUpgradeable.sol, packages/contracts/src/core/utils/BitMap.sol, packages/contracts/src/framework/plugin/repo/PluginRepo.sol, packages/contracts/src/framework/plugin/setup/IPluginSetup.sol, packages/contracts/src/framework/plugin/setup/PluginSetup.sol, packages/contracts/src/framework/plugin/setup/PluginSetupProcessorHelpers.sol, packages/contracts/src/framework/utils/TokenFactory.sol, packages/contracts/src/plugins/governance/admin/Admin.sol, packages/contracts/src/plugins/governance/majority-voting/IMajorityVoting.sol, packages/contracts/src/plugins/governance/majority-voting/MajorityVotingBase.sol, packages/contracts/src/plugins/governance/majority-voting/addresslist/AddresslistVoting.sol, packages/contracts/src/plugins/governance/majority-voting/token/TokenVoting.sol, packages/contracts/src/plugins/governance/multisig/IMultisig.sol, packages/contracts/src/plugins/governance/multisig/Multisig.sol, packages/contracts/src/plugins/token/MerkleDistributor.sol, packages/contracts/src/plugins/token/MerkleMinter.sol, packages/contracts/src/token/ERC20/governance/GovernanceERC20.sol, packages/contracts/src/token/ERC20/governance/GovernanceWrappedERC20.sol, packages/contracts/src/utils/Proxy.sol
Many NatSpec `/// @return` comments included the data type, which would then be displayed twice
=> NatSpec: Fix duplicated display of the data type in NatSpec `/// @return` comments

packages/contracts/src/core/permission/PermissionManager.sol
Task: [APP-1909](https://aragonassociation.atlassian.net/browse/APP-1909)
[APP-1909]: https://aragonassociation.atlassian.net/browse/APP-1909?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Documented the behavior of revoking with `who` or `where` equal to `ANY_ADDR`

packages/contracts/test/token/erc20/governance-erc20.ts, packages/contracts/test/token/erc20/governance-wrapped-erc20.ts
Added more tests after the discovery that was fixed in #285 
Task: [APP-1865](https://aragonassociation.atlassian.net/browse/APP-1865)
[APP-1865]: https://aragonassociation.atlassian.net/browse/APP-1865?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
```
afterTokenTransfer
...
exhaustive tests
`to` has a zero-balance
`to` delegated to `other`
`to` receives via mint from `address(0)`
✓ `to` has the correct voting power
✓ `to`s delegate has not changed
✓ `to`s delegate has the correct voting power
`to` receives via transfer from `from`
✓ `from` has the correct voting power
✓ `from`s delegate has not changed
✓ `from`s delegate has the correct voting power
✓ `to` has the correct voting power
✓ `to`s delegate has not changed
✓ `to`s delegate has the …
```
=> Added exhaustive tests for the governance tokens

packages/contracts/deploy/00_managing-dao/00_managing-dao.ts, packages/contracts/deploy/40_finalize-managing-dao/00_grant-permissions.ts, packages/contracts/deploy/40_finalize-managing-dao/20_register-managing-dao-on-dao-registry.ts, packages/contracts/deploy/40_finalize-managing-dao/40_revoke-permissions.ts
=> fix metadata

README.md, packages/contracts/README.md, packages/contracts/docs/osx/02-how-to-guides/02-plugin-development/index.md
The current plugin development docs still had the old package name `@aragon/core-contracts` so devs are getting errors when installing.
Just updated the name to `@aragon/osx-contracts`.
Task: [ID]()
- [n/a] I have commented my code, particularly in hard-to-understand areas.
- [n/a] My changes generate no new warnings.
- [n/a] Any dependent changes have been merged and published in downstream modules.
- [n/a] I ran all tests with success and extended them if necessary.
- [n/a] I have updated the ``CHANGELOG.md`` file in the root folder.
- [n/a] I have tested my code on the test network.
=> Fixing npm package name

packages/subgraph/CHANGELOG.md, packages/subgraph/package.json, packages/subgraph/src/registries/daoRegistry.ts, packages/subgraph/tests/registry/daoRegistry.test.ts
=> feat: adds blocklist to remove subdomains from indexing

packages/contracts/package.json, packages/contracts/src/package.json
After doing this, I realized one thing. If you install `@aragon/osx`, it's true, it brings the contracts in the node_modules, but they won't work unless consumer of our package installs `openzeppelin packages` by himself. Isn't the whole idea why dev would install our package to build on top of it ? 
Maybe in the `packages/contracts/src/package.json`, we should put OZ packages in the `dependencies` . 
@brickpop @mathewmeconry 
Task: [ID]()
=> move to dev dependency

packages/contracts/docs/osx/01-how-it-works/01-core/02-permissions/01-conditions.md, packages/contracts/docs/osx/01-how-it-works/02-framework/02-plugin-management/01-plugin-repo/01-plugin-repo-creation.md, packages/contracts/docs/osx/01-how-it-works/02-framework/02-plugin-management/01-plugin-repo/index.md, packages/contracts/docs/osx/02-how-to-guides/02-plugin-development/03-non-upgradeable-plugin/01-initialization.md
Addressed code4arena findings in the docs
Task: [None]()
=> Addressed code4arena findings in the docs

packages/contracts/CHANGELOG.md, packages/contracts/src/plugins/governance/multisig/Multisig.sol, packages/contracts/test/plugins/governance/multisig/multisig.ts
When the Multisig settings and addresses are updated and in the same block another proposal gets created an attacker could trigger a race condition:
Consider the addresses 0x01, 0x02, 0x03 to be a member of the Multisig, and the minApprovals is set to 2 during block 1.
Now 0x03 is considered a bad actor and a proposal is created and approved by 0x01 and 0x02 during block 2 but not yet executed to remove 0x03 from the member list and reduce minApprovals to 1.
0x03 can now swoop in with a MEV sandwich block 3 and execute the proposal and create a new proposal in the same block and auto-execute it resulting in 0x03 taking over the Multisig.
This problem is because `createProposal()` uses the members list from the previous block (2) but the new settings from block 3 resulting in 0x03 still …
=> fix: fixes vuln in Multisig Plugin

packages/contracts/CHANGELOG.md, packages/contracts/src/core/dao/DAO.sol, packages/contracts/src/core/dao/IDAO.sol, packages/contracts/src/test/dao/GasConsumerHelper.sol, packages/contracts/test/core/dao/dao.ts
**Code4rena Finding:** https://github.com/code-423n4/2023-03-aragon-findings/issues/191
=> Fix 1/64 problem in DAO executor

DEPLOYMENT_CHECKLIST.md, packages/contracts/CHANGELOG.md, packages/contracts/src/core/dao/DAO.sol, packages/contracts/src/utils/protocol/IProtocolVersion.sol, packages/contracts/src/utils/protocol/ProtocolVersion.sol, packages/contracts/test/upgrade/dao.ts
Task: [OS-387](https://aragonassociation.atlassian.net/browse/OS-387)
[OS-387]: https://aragonassociation.atlassian.net/browse/OS-387?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> F/  OS-387 add protocol version

packages/contracts/CHANGELOG.md, packages/contracts/test/upgrade/dao.ts, packages/subgraph/CHANGELOG.md, packages/subgraph/manifest/subgraph.placeholder.yaml, packages/subgraph/src/dao/dao_v1_3_0.ts, packages/subgraph/src/packages/addresslist/addresslist-voting.ts, packages/subgraph/src/packages/token/token-voting.ts, packages/subgraph/src/registries/daoRegistry.ts, packages/subgraph/tests/dao/dao_v1_3_0.test.ts
Task: [OS-459](https://aragonassociation.atlassian.net/browse/OS-459)
QA: https://subgraph.satsuma-prod.com/aragon/jose-goerli/version/srkwt-debug-date1/playground
querry:
`
tokenVotingProposals {
startDate
endDate
}
`
[OS-459]: https://aragonassociation.atlassian.net/browse/OS-459?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OS-459 : Subgraph update to v1.3.0

UPDATE_CHECKLIST.md, packages/contracts/src/plugins/governance/multisig/build-metadata.json
There is no build 2 for Multisig
Task: [OS-524](https://aragonassociation.atlassian.net/browse/OS-524)
[OS-524]: https://aragonassociation.atlassian.net/browse/OS-524?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: corrected build metadata

packages/contracts/CHANGELOG.md, packages/contracts/docs/osx/01-how-it-works/01-core/02-permissions/01-conditions.md, packages/contracts/docs/osx/01-how-it-works/01-core/02-permissions/index.md, packages/contracts/src/core/permission/PermissionCondition.sol, packages/contracts/src/core/permission/PermissionConditionBase.sol, packages/contracts/src/core/permission/PermissionConditionUpgdaeable.sol, packages/contracts/src/core/permission/PermissionManager.sol, packages/contracts/src/test/permission/ParameterScopingPermissionConditionTest.sol, packages/contracts/src/test/permission/PermissionConditionMock.sol, packages/contracts/src/test/plugin/SharedPluginTest.sol, packages/contracts/test/core/permission/permission-manager.ts
Adds ERC-165  (`supportsInterface()`) to `IPermissionCondition` implementations by providing an abstract base class for implementers to inherit from.
This allows detection if a contract provided in `grantWithCondition` is really an `IPermissionCondition` contract. This is an important feature to prevent accidental bricking of the DAO by providing a wrong condition address.
Task: [OS-521](https://aragonassociation.atlassian.net/browse/OS-521)
[OS-521]: https://aragonassociation.atlassian.net/browse/OS-521?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ERC-165 support for PermissionConditions

packages/contracts/CHANGELOG.md, packages/contracts/deploy/new/30_plugins/00_plugin-setups/10_token_voting_setup.ts, packages/contracts/deploy/new/30_plugins/00_plugin-setups/11_token_voting_setup_conclude.ts, packages/contracts/deploy/update/to_v1.3.0/41_TokenVoting_Plugin.ts, packages/contracts/deploy/update/to_v1.3.0/42_TokenVoting_Plugin_conclude.ts, packages/contracts/src/plugins/governance/majority-voting/token/TokenVotingSetup.sol, packages/contracts/test/plugins/governance/majority-voting/token/token-voting-setup.ts
This PR provides the `GovernanceERC20` and `GovernanceWrappedERC20` token bases to the `TokenVotingSetup` constructor as arguments to avoid the `initCode` size limit on the Goerli testnet.
Note that the `TokenVoting` implementation remains intentionally in the constructor because the setup and implementation should never be out of sync.
Task: [ID]()
=> Provide Governance Token Bases to `TokenVotingSetup` Constructor as Arguments to Avoid `initCode` size limit on Goerli

packages/contracts/docs/osx/01-how-it-works/02-framework/02-plugin-management/01-plugin-repo/01-plugin-repo-creation.md, packages/contracts/docs/osx/01-how-it-works/02-framework/02-plugin-management/02-plugin-setup/index.md, packages/contracts/docs/osx/01-how-it-works/02-framework/02-plugin-management/index.md, packages/contracts/docs/osx/01-how-it-works/02-framework/index.md, packages/contracts/docs/osx/01-how-it-works/index.md, packages/contracts/docs/osx/02-how-to-guides/01-dao/03-protocol-upgrades.md, packages/contracts/docs/osx/02-how-to-guides/01-dao/04-managing-plugins/index.md, packages/contracts/docs/osx/02-how-to-guides/02-plugin-development/01-best-practices.md, packages/contracts/docs/osx/02-how-to-guides/02-plugin-development/03-non-upgradeable-plugin/01-initialization.md, packages/contracts/docs/osx/02-how-to-guides/02-plugin-development/03-non-upgradeable-plugin/02-implementation.md, packages/contracts/docs/osx/02-how-to-guides/02-plugin-development/03-non-upgradeable-plugin/03-setup.md, packages/contracts/docs/osx/02-how-to-guides/02-plugin-development/03-non-upgradeable-plugin/index.md, packages/contracts/docs/osx/02-how-to-guides/02-plugin-development/04-upgradeable-plugin/01-initialization.md, packages/contracts/docs/osx/02-how-to-guides/02-plugin-development/04-upgradeable-plugin/02-implementation.md, packages/contracts/docs/osx/02-how-to-guides/02-plugin-development/04-upgradeable-plugin/03-setup.md, packages/contracts/docs/osx/02-how-to-guides/02-plugin-development/04-upgradeable-plugin/04-subsequent-builds.md, packages/contracts/docs/osx/02-how-to-guides/02-plugin-development/04-upgradeable-plugin/05-updating-versions.md, packages/contracts/docs/osx/02-how-to-guides/02-plugin-development/04-upgradeable-plugin/index.md, packages/contracts/docs/osx/02-how-to-guides/02-plugin-development/05-governance-plugins/index.md, packages/contracts/docs/osx/02-how-to-guides/02-plugin-development/07-publication/01-versioning.md, packages/contracts/docs/osx/02-how-to-guides/02-plugin-development/07-publication/index.md, packages/contracts/docs/osx/02-how-to-guides/02-plugin-development/index.md, packages/contracts/docs/osx/03-reference-guide/index.md, packages/contracts/docs/osx/index.md
Based on previous reviews and how the Developer Portal is showcasing names, I've decided to go back to the short naming conventions we had before. 
Additionally, I've improved the titles so they're consistent across plugin types.
Task: [DX-56](https://aragonassociation.atlassian.net/jira/software/projects/DX/boards/56?selectedIssue=DX-56)
Documentation
[DX-56]: https://aragonassociation.atlassian.net/browse/DX-56?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Improve index naming

packages/subgraph/CHANGELOG.md, packages/subgraph/manifest/subgraph.placeholder.yaml, packages/subgraph/package.json, packages/subgraph/src/plugin/utils.ts, packages/subgraph/src/utils/constants.ts
Task: [OS-545](https://aragonassociation.atlassian.net/browse/OS-545)
Note: since the subgraphs are deployed manually, we will not add labels to deploy subgraph via github actions, we only bump the version of the subgraph on this repo.
[OS-545]: https://aragonassociation.atlassian.net/browse/OS-545?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OS-545 : fix indexing ERC20Wrapped

packages/contracts/docs/osx/01-how-it-works/01-core/03-plugins/index.md, packages/contracts/docs/osx/01-how-it-works/01-core/index.md, packages/contracts/docs/osx/01-how-it-works/02-framework/02-plugin-management/01-plugin-repo/index.md, packages/contracts/docs/osx/01-how-it-works/02-framework/02-plugin-management/index.md, packages/contracts/docs/osx/02-how-to-guides/01-dao/04-managing-plugins/index.md, packages/contracts/docs/osx/02-how-to-guides/02-plugin-development/index.md
As I was reading the [OSx documentation](https://devs.aragon.org/docs/osx/), I found some small typos and formatting issues that have been fixed on this PR.
=> Fix: typos and formatting issues on documentation

DEPLOYMENT_CHECKLIST.md, UPDATE_CHECKLIST.md
=> docs(OS-692): adds github release info to checklists

packages/contracts/src/core/dao/DAO.sol, packages/contracts/test/core/dao/dao.ts
Task: [OS-719](https://aragonassociation.atlassian.net/browse/OS-719)
[OS-719]: https://aragonassociation.atlassian.net/browse/OS-719?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: forgotten reinitializer bump

README.md, packages/contracts-ethers/README.md, packages/contracts/README.md, packages/subgraph/README.md
Task: [OS-704](https://aragonassociation.atlassian.net/browse/OS-704)
[OS-704]: https://aragonassociation.atlassian.net/browse/OS-704?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore/ OS-704 Add security contact to the readme(s)

packages/contracts/src/test/Migration.sol, packages/contracts/test/core/dao/dao.ts, packages/contracts/test/interfaces.ts, packages/contracts/test/plugins/governance/admin/admin-setup.ts, packages/contracts/test/plugins/governance/admin/admin.ts, packages/contracts/test/plugins/governance/majority-voting/addresslist/addresslist-voting-setup.ts, packages/contracts/test/plugins/governance/majority-voting/addresslist/addresslist-voting.ts, packages/contracts/test/plugins/governance/majority-voting/token/token-voting-setup.ts, packages/contracts/test/plugins/governance/majority-voting/token/token-voting.ts, packages/contracts/test/plugins/governance/multisig/multisig-setup.ts, packages/contracts/test/plugins/governance/multisig/multisig.ts, packages/contracts/test/test-utils/interfaces.ts, packages/contracts/test/token/erc20/governance-wrapped-erc20.ts, packages/subgraph/src/plugin/utils.ts, packages/subgraph/src/utils/constants.ts, packages/subgraph/src/utils/tokens/erc20.ts, packages/subgraph/tests/plugin/pluginSetupProcessor.test.ts, packages/subgraph/tests/token/token-voting.test.ts
Task: [OS-694](https://aragonassociation.atlassian.net/browse/OS-694)
[OS-694]: https://aragonassociation.atlassian.net/browse/OS-694?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> test: add interface tests and subgraph renaming

packages/contracts/src/plugins/governance/admin/build-metadata.json, packages/contracts/src/plugins/governance/majority-voting/addresslist/build-metadata.json, packages/contracts/src/plugins/governance/majority-voting/token/build-metadata.json, packages/contracts/src/plugins/governance/multisig/build-metadata.json
The `prepareUpdate` and `prepareUninstallation` ABI definition should be alongside `prepareInstallation` and not a child of it.
=> Amending incorrect build metadata hierarchy

packages/contracts/CHANGELOG.md
Task: [OS-761](https://aragonassociation.atlassian.net/browse/OS-761)
[OS-761]: https://aragonassociation.atlassian.net/browse/OS-761?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: maintained changelog

packages/contracts/CHANGELOG.md, packages/contracts/src/core/dao/DAO.sol, packages/contracts/src/test/utils/VersionComparisonLibTest.sol, packages/contracts/src/utils/protocol/VersionComparisonLib.sol, packages/contracts/test/utils/version-comparison-lib.ts
Task ID: [OS-723](https://aragonassociation.atlassian.net/browse/OS-723)
[OS-723]: https://aragonassociation.atlassian.net/browse/OS-723?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: added semver comparision lib

packages/contracts/test/core/dao/dao.ts, packages/contracts/utils/event.ts, packages/subgraph/CHANGELOG.md, packages/subgraph/manifest/subgraph.placeholder.yaml, packages/subgraph/src/dao/dao_v1_0_0.ts, packages/subgraph/tests/dao/dao_v1_0_0.test.ts, packages/subgraph/tests/dao/utils.ts
Task: [OS-724](https://aragonassociation.atlassian.net/browse/OS-724)
- The `SignatureValidatorSet` was not used anywhere so removal does not qualify as a breaking change
[OS-724]: https://aragonassociation.atlassian.net/browse/OS-724?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> refactor: removed deprecated SignatureValidatorSet event from subgraph

.github/workflows/subgraph-deploy.yaml
=> ci(OS-798): use base_ref as default instead of head_ref

.github/workflows/documentation-update.yml, packages/contracts/docs/developer-portal/04-framework-lifecycle/01-systems.md, packages/contracts/docs/developer-portal/04-framework-lifecycle/02-semver.md, packages/contracts/docs/developer-portal/04-framework-lifecycle/03-osx-components/01-factory-contract.md
https://github.com/aragon/developer-portal/actions/runs/6960853849/job/18941202352?pr=132
- docs
=> docs: fix broken dev-portal link and exclude framework lifecylce docs

packages/subgraph/CHANGELOG.md, packages/subgraph/package.json, packages/subgraph/schema.graphql, packages/subgraph/scripts/deploy-subgraph.sh, packages/subgraph/src/packages/addresslist/addresslist-voting.ts, packages/subgraph/src/packages/multisig/multisig.ts, packages/subgraph/src/packages/token/token-voting.ts, packages/subgraph/tests/addresslist-voting/addresslist-voting.test.ts, packages/subgraph/tests/addresslist-voting/utils.ts, packages/subgraph/tests/helpers/method-classes.ts, packages/subgraph/tests/multisig/multisig.test.ts, packages/subgraph/tests/multisig/utils.ts, packages/subgraph/tests/token/token-voting.test.ts, packages/subgraph/tests/token/utils.ts
Task ID: [OS-855](https://aragonassociation.atlassian.net/browse/OS-855)
Test subgraph: https://subgraph.satsuma-prod.com/aragon/osx-michael-baseGoerli/playground
[OS-855]: https://aragonassociation.atlassian.net/browse/OS-855?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> refactor: signalling proposal subgraph change

DEPLOYMENT_CHECKLIST.md, UPDATE_CHECKLIST.md, packages/contracts/deploy/helpers.ts
Task ID: [OS-901](https://aragonassociation.atlassian.net/browse/OS-901) (surfaced in spike [OS-899](https://aragonassociation.atlassian.net/browse/OS-899))
**After merging this PR, the `main` branch must be merged into `develop`.**
The inputs to `createVersion` in `packages/contracts/src/framework/plugin/repo/PluginRepo.sol` are as follows:
```solidity
function createVersion(
uint8 _release,
address _pluginSetup,
bytes calldata _buildMetadata,
bytes calldata _releaseMetadata
) 
```
([see here](https://github.com/aragon/osx/blob/40f342b5906681e0050ec8bb984fc331070b932a/packages/contracts/src/framework/plugin/repo/PluginRepo.sol#L130-L136))
However, it was used here with the arguments being mixed up in the helpers `packages/contracts/deploy/helpers.ts`
```ts
export async function …
```
=> fix: build and release metadata mixups

packages/contracts/deploy/update/to_v1.3.0/60_Admin_PluginRepo.ts, packages/contracts/deploy/verification/99_conclude/01_managing_dao_proposal.ts
Task ID: [OS-898](https://aragonassociation.atlassian.net/browse/OS-898)
[OS-898]: https://aragonassociation.atlassian.net/browse/OS-898?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> deploy(contracts): improves management DAO proposal readability

DEPLOYMENT_CHECKLIST.md, UPDATE_CHECKLIST.md, packages/contracts/src/plugins/governance/admin/Admin.sol, packages/contracts/src/plugins/governance/admin/AdminSetup.sol, packages/contracts/src/plugins/governance/majority-voting/addresslist/AddresslistVoting.sol, packages/contracts/src/plugins/governance/majority-voting/addresslist/AddresslistVotingSetup.sol, packages/contracts/src/plugins/governance/majority-voting/token/TokenVoting.sol, packages/contracts/src/plugins/governance/majority-voting/token/TokenVotingSetup.sol, packages/contracts/src/plugins/governance/multisig/Multisig.sol, packages/contracts/src/plugins/governance/multisig/MultisigSetup.sol
Task ID: [OS-896](https://aragonassociation.atlassian.net/browse/OS-896)
- docs
[OS-896]: https://aragonassociation.atlassian.net/browse/OS-896?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs(contracts): added version numbers to plugin implementations and setups

packages/contracts/hardhat.config.ts, packages/contracts/src/framework/plugin/setup/PluginSetupProcessor.sol, packages/contracts/test/framework/utils/ens/ens-subdomain-registry.ts
Task ID: [OS-1013](https://aragonassociation.atlassian.net/browse/OS-1013)
[OS-1013]: https://aragonassociation.atlassian.net/browse/OS-1013?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: wrong import, missing await, incorrect comment

README.md
Changes in the package README files for new contributors. Full 
details [here](https://www.notion.so/aragonorg/Notes-on-Running-the-OSx-Repo-for-the-first-time-8db2cef330a84dbeb858726e441d4c3b)
**Warn users about certain node versions:**
_I decided to avoid an `.nvmrc` or any `package.json` engines because dependencies may be updated shortly and I don't want to break downstream users CI pipelines. A readme will suffice for now_
Task ID: [OS-1036](https://aragonassociation.atlassian.net/browse/OS-1036)
[OS-1036]: https://aragonassociation.atlassian.net/browse/OS-1036?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: specify range of node versions in readme and advise cd into package

packages/contracts/deploy/helpers.ts, packages/contracts/hardhat.config.ts, packages/contracts/networks.ts, packages/contracts/test/framework/plugin/plugin-setup-processor.ts, packages/contracts/types/hardhat.d.ts
Fixed HRE extension compiler warnings: changed module exports from `hardhat/types` -> `hardhat/types/runtime`. This also fixes type errors in all deploy scripts.
Added casting to fix 2 errors in the HH config and the networks file. I believe these are safe casts but we should discuss about having 2 separate `SupportedNetworks` enums when really we should have 1 coming from the commons. 
Removed Arbitrum Goerli and added base and arb sepolia to the networks, to align with supported networks and thus allow us to correctly index the networks in hardhat.config.
The only oddity was having to add a chai listener for defi wonderland. This was required for me to run the test suite so would appreciate a sanity check on why that might be.
This addresses 2 tickets: …
=> fix: updated typings in HRE declaration and type errors in helpers

packages/contracts/README.md, packages/contracts/test/chai-setup.ts, packages/contracts/test/framework/plugin/plugin-setup-processor.ts
Chai requires binding matchers to the global test runner inside hardhat, not doing so leaves certain tests in the PSP to throw due to the matchers not being found.
The fix is to use
chai.use(smock.matchers);
But rather than write in every test file, we should define a setup script:
```ts
/**
* Enable additional matchers for chai and smock
* import this file in place of chai, i.e:
* import {expect} from './chai-setup';
**/
import {smock} from '@defi-wonderland/smock';
import chai from 'chai';
chai.use(smock.matchers);
export = chai;
```
Which can then be imported in place of Chai, in a consistent manner for all files.
`import {expect} from './chai-setup'`
Note: in theory there is a require field in the mocha config in hardhat. This doesn’t appear to actually run any scripts before the …
=> Add chai-setup script to consistently import additional matchers 

packages/subgraph/CHANGELOG.md, packages/subgraph/package.json, packages/subgraph/src/packages/addresslist/addresslist-voting.ts, packages/subgraph/src/packages/multisig/multisig.ts, packages/subgraph/src/packages/token/token-voting.ts, packages/subgraph/src/plugin/pluginRepo.ts, packages/subgraph/src/utils/tokens/erc20.ts, packages/subgraph/src/utils/tokens/eth.ts, packages/subgraph/tests/addresslist-voting/addresslist-voting.test.ts, packages/subgraph/tests/admin/admin.test.ts, packages/subgraph/tests/constants.ts, packages/subgraph/tests/dao/dao_v1_0_0.test.ts, packages/subgraph/tests/dao/dao_v1_3_0.test.ts, packages/subgraph/tests/helpers/method-classes.ts, packages/subgraph/tests/multisig/multisig.test.ts, packages/subgraph/tests/plugin/pluginSetupProcessor.test.ts, packages/subgraph/tests/token/token-voting.test.ts, packages/subgraph/tests/utils.ts, yarn.lock
Use createDummyAction and Token calls generator from the @aragon/osx-commons-subgraph
Task ID: [OS-999](https://aragonassociation.atlassian.net/browse/OS-999)
[OS-999]: https://aragonassociation.atlassian.net/browse/OS-999?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: use common mocks and token calls generators

packages/contracts/test/deploy/default-env.ts, packages/contracts/utils/environment.ts
@Michael-A-Heuer asked me to change `plugin.dao.eth` as a fallback value from `plugin.eth`. This small change was missed in the previous PR and so adding it here. 
Task ID: [OS-1069](https://aragonassociation.atlassian.net/browse/OS-1069)
[OS-1069]: https://aragonassociation.atlassian.net/browse/OS-1069?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix typo in fallback value

packages/contracts/docs/developer-portal/01-how-it-works/01-core/01-dao/index.md, packages/contracts/docs/developer-portal/01-how-it-works/02-framework/01-dao-creation/index.md, packages/contracts/docs/developer-portal/01-how-it-works/02-framework/02-plugin-management/01-plugin-repo/01-plugin-repo-creation.md, packages/contracts/docs/developer-portal/01-how-it-works/02-framework/02-plugin-management/01-plugin-repo/index.md, packages/contracts/docs/developer-portal/01-how-it-works/02-framework/02-plugin-management/02-plugin-setup/01-security-risk-mitigation.md, packages/contracts/docs/developer-portal/01-how-it-works/02-framework/03-ens-names.md, packages/contracts/docs/developer-portal/02-how-to-guides/01-dao/02-action-execution.md, packages/contracts/docs/developer-portal/02-how-to-guides/02-plugin-development/06-meta-tx-plugins.md, packages/contracts/docs/developer-portal/02-how-to-guides/02-plugin-development/07-publication/02-metadata.md
Fixed some links that will generate a broken links error in Developer-Portal because of the update of Docusaurus from v2 to v3.
Removed some extra `/` that were generating this error.
Deleted an outdated markdown link (was pointing to a paragraph of another page that no longer exists).
Added some closing parenthesis `)` that I spotted while fixing links (haven't reviewed documentation, just fixed spotted ones).
Task ID: [OS-1070](https://aragonassociation.atlassian.net/browse/OS-1070)
[OS-1070]: https://aragonassociation.atlassian.net/browse/OS-1070?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ci: Manual fixes in documentation, fixing links. Add some closing `)`

packages/subgraph/schema.graphql
To generate the documentation for Subgraph, we are going to use the introspection query, which will read from the schema.graphql itself because the API Endpoint introduces a lot of redundant information.
To do so, we need to declare the scalars Bytes and BigInt that don't exist in GraphQL (the comments are optional, I added so if someone reaches them in the documentation).
And also we need to initialize a Query type, again the comments are optional.
Task ID: [OS-1136](https://aragonassociation.atlassian.net/browse/OS-1136)
[OS-1136]: https://aragonassociation.atlassian.net/browse/OS-1136?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Subgraph: Helpers for Introspection Query

packages/subgraph/package.json
Bumps subgraphs package.json to 1.4.1 to address bugs regarding negative token balances and missing delegations.
We will invoke the github action to build and deploy the subgraphs against 1.4.1
[Spike is documented here](https://www.notion.so/aragonorg/Subgraph-Deploy-YAML-fb3d4dc6e86c4f11b64eca89b2011a53?pm=c) explaining a bit more about the deploy process.
Task ID: [OS-1116](https://aragonassociation.atlassian.net/browse/OS-1116)
- [] I have updated the `UPDATE_CHECKLIST` file in the root folder.
[OS-1116]: https://aragonassociation.atlassian.net/browse/OS-1116?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: bump package.json in readiness for gh workflow

.github/pull_request_template.md, CONTRIBUTION_GUIDE.md
On the fly task to add a QA checklist item to the list below
=> docs: add a checklist item to PR template && fix broken link

.github/workflows/documentation-update.yml
This PR updates the documentation-updated workflow to define the alchemy key in the workflow env
To check the change works properly needed to run the workflow and it only runs when pushing to `develop`. To avoid pushing not-tested code to `develop` in the commit https://github.com/aragon/osx/pull/558/commits/11485f914b2bf7a28970020ac782b5c5c764a53c added the current branch to force the workflow to run. 
The workflow running successfuly can be seen [here](https://github.com/aragon/osx/actions/runs/8442466798/job/23123924943)
Task ID: [OS-1166](https://aragonassociation.atlassian.net/browse/OS-1166)
[OS-1166]: …
=> fix: update documentation workflow

packages/subgraph/README.md
The PR adds an explanation about how how Aragon uses extended classes to ease the testing for subgraph.
Task ID: [OS-1168](https://aragonassociation.atlassian.net/browse/OS-1168)
[OS-1168]: https://aragonassociation.atlassian.net/browse/OS-1168?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add explanation for testing subgraph extended classes

packages/subgraph/schema.graphql, packages/subgraph/src/packages/multisig/multisig.ts, packages/subgraph/tests/addresslist-voting/addresslist-voting.test.ts, packages/subgraph/tests/multisig/multisig.test.ts, packages/subgraph/tests/token/governance-erc20.test.ts
Some approvers did not appear as approvers on past proposals after they've been removed from the multisig because the entity for the multisift members and approvers was related. 
This fixes this issue using the solution discussed here: https://www.notion.so/aragonorg/Subgraph-Bug-Approvers-Query-Breaks-Multisig-Subgraph-d783e196ba464595974ba2a9d2dac80a#5ca1bd831bbd4dc191dd8fb0d4360e8f 
Task ID: [OS-1224](https://aragonassociation.atlassian.net/browse/OS-1224)
Playground: https://subgraph.satsuma-prod.com/aragon/osx-test-members-bug-mainnet/version/5/playground
[OS-1224]: https://aragonassociation.atlassian.net/browse/OS-1224?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3 …
=> F/OS-1224 Multisig approvers not appearing in past proposals

packages/contracts/src/plugins/governance/multisig/Multisig.sol, packages/contracts/test/plugins/governance/multisig/multisig.ts
Fix revert params order in `removeAddresses`function
Task ID: [OS-1299](https://aragonassociation.atlassian.net/browse/OS-1299)
[OS-1299]: https://aragonassociation.atlassian.net/browse/OS-1299?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: multisig removeAddresses revert param order

packages/subgraph/CHANGELOG.md, packages/subgraph/schema.graphql, packages/subgraph/src/registries/daoRegistry.ts, packages/subgraph/tests/dao/utils.ts, packages/subgraph/tests/helpers/method-classes.ts, packages/subgraph/tests/registry/daoRegistry.test.ts
Pr for adding the tx hash field in the subgraph Dao entity. 
[QA subgraph deployed](https://subgraphs.alchemy.com/subgraphs/5350/versions/17509)
Task ID: [OS-1181](https://aragonassociation.atlassian.net/browse/OS-1181)
[OS-1181]: https://aragonassociation.atlassian.net/browse/OS-1181?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add tx hash to dao entity in subgraph

.github/workflows/contract-tests.yml, DEPLOYMENT_CHECKLIST.md, packages/contracts/README.md, packages/contracts/deploy/new/40_finalize-managing-dao/20_register-managing-dao-on-dao-registry.ts, packages/contracts/deploy/new/40_finalize-managing-dao/40_revoke-permissions.ts, packages/contracts/src/README.md, packages/contracts/test/deploy/managing-dao.ts
The  management DAO ENS subdomain env var name was not updated after we changed it from 
`MANAGINGDAO_SUBDOMAIN ` to `MANAGEMENT_DAO_SUBDOMAIN`.
=> fix: wrong env name

packages/contracts/CHANGELOG.md, packages/contracts/src/framework/plugin/repo/IPluginRepo.sol, packages/contracts/src/framework/plugin/repo/PluginRepo.sol, packages/contracts/test/framework/plugin/plugin-repo.ts
- we can move the events to the right place without changing the ERC-165 interface ID and updating the PluginRepoFactory
- check on DAO.sol how this function is supposed to work
- if we don’t need to re-initialize, then this function will be empty for now.
Task ID: [OS-676](https://aragonassociation.atlassian.net/browse/OS-676)
[OS-676]: https://aragonassociation.atlassian.net/browse/OS-676?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> refactor: added reinitializer and storage gap to `PluginRepo` and moved events to `IPluginRepo`

packages/contracts/src/core/dao/DAO.sol, packages/contracts/test/core/dao/dao.ts
=> add tests and fixes to dao

packages/contracts/src/core/permission/PermissionManager.sol, packages/contracts/test/core/permission/permission-manager.ts, packages/contracts/test/framework/dao/dao-factory.ts
=> fix more tests and cleaner

packages/contracts/test/framework/dao/dao-factory.ts
=> feat: improve some test checks

packages/contracts/utils/etherscan.ts
Fix import in etherscan utils file
Task ID: [OS-1479](https://aragonassociation.atlassian.net/browse/OS-1479)
[OS-1479]: https://aragonassociation.atlassian.net/browse/OS-1479?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: deploy scripts issue
