- .github/ISSUE_TEMPLATE/bug_report.md
I've overtook the existing bug report issue template from aragon/sdk.
> Adds the bug report issue template

- .github/workflows/contract-tests.yml
- packages/contracts/npm/artifacts.ts
- Updating the path of the factory and voting contracts
- Adding a step to also build the JSON artifacts for NodeJS on the CI/CD pipeline
> Update the JSON artifact paths

- packages/contracts-ethers/CHANGELOG.md
- packages/contracts-ethers/package.json
- packages/contracts/CHANGELOG.md
- packages/contracts/package.json
- Updates the package.json files to make NPM packages public
- Creates the changelog files
> Public NPM packages

- packages/subgraph/.eslintignore
- packages/subgraph/.eslintrc.json
- packages/subgraph/package.json
- packages/subgraph/src/dao/utils.ts
- packages/subgraph/src/packages/whitelist/whitelistVoting.ts
- packages/subgraph/src/utils/erc165.ts
- packages/subgraph/src/utils/metadata.ts
- packages/subgraph/tests/ERC20Voting/erc20Voting.test.ts
- packages/subgraph/tests/ERC20Voting/utils.ts
- packages/subgraph/tests/dao/acl.test.ts
- packages/subgraph/tests/dao/dao.test.ts
- packages/subgraph/tests/dao/utils.ts
- packages/subgraph/tests/registry/registry.test.ts
- packages/subgraph/tests/registry/utils.ts
- packages/subgraph/tests/whitelistVoting/utils.ts
- packages/subgraph/tests/whitelistVoting/whitelistVoting.test.ts
- yarn.lock
- add eslint
- clean subgraph testing
Task: [ID](https://aragonassociation.atlassian.net/browse/DAO-808)
> Feature/ DAO-808

- .github/workflows/contracts-deploy.yml
- .github/workflows/npm-release.yml
- packages/contracts-ethers/package.json
> feat: adds workflow for npm releases

- .github/workflows/contracts-deploy.yml
- .github/workflows/npm-release-reusable.yml
- .github/workflows/npm-release.yml
Fixes node version for rollup js
Fixes simultaneous runs with npm-release and contracts deploy
> fix: npm release flow if contracts are also changed

- .github/workflows/contracts-deploy.yml
- .github/workflows/create-dummy-dao.yml
- .github/workflows/npm-release-reusable.yml
- .github/workflows/npm-release.yml
> fix: secrets handling in contract workflows

- .github/workflows/npm-release-reusable.yml
> fix: working directory for npm publishing

- .github/workflows/npm-release.yml
> fix: npm filter check to deploy if no contracts have changed

- .github/workflows/npm-release-reusable.yml
> fix: adds missing npm registry

- packages/contracts/CHANGELOG.md
- packages/contracts/contracts/factory/TokenFactory.sol
- packages/contracts/contracts/tokens/IERC20MintableUpgradeable.sol
- packages/contracts/contracts/tokens/MerkleDistributor.sol
- packages/contracts/contracts/tokens/MerkleMinter.sol
- packages/contracts/test/merkle/merkle-distributor.ts
- packages/contracts/test/merkle/merkle-minter.ts
`MerkleMinter` uses `GovernanceERC20` despite the possibility to be more general (by using `IERC20`).
This way, a `MerkleMinter` `MetaTxComponent` could be used to mint any kind of token.
Task: [APP-286](https://aragonassociation.atlassian.net/browse/APP-286)
> Componentize and generalize MerkleMinter

- packages/contracts/CHANGELOG.md
- packages/contracts/contracts/factory/TokenFactory.sol
- packages/contracts/test/core/token-factory.ts
Task: [ID](https://aragonassociation.atlassian.net/browse/APP-343)
> Featur/ APP-343 allow mint token to treasury

- .github/workflows/npm-release-reusable.yml
> fix: version publishing in workflow

- .github/workflows/mythx-changed.yaml
- .github/workflows/mythx-full.yaml
- .gitignore
- .mythx.yml
Adds the necessary workflows to run myhtx against changed files or do a full scan against all contracts.
Task: DOPS-314
> feat: adds workflows to run mythx against the contracts

- packages/contracts/CHANGELOG.md
- packages/contracts/contracts/plugin/PluginRepo.sol
- packages/contracts/test/plugin/plugin-repo.ts
Task: [ID](https://aragonassociation.atlassian.net/browse/APP-786)
> APP-786 Update repo to be compatible with Aragon plugin

- .github/workflows/comment-triggers.yml
> fix: comment-trigger workflow

- .github/workflows/comment-triggers.yml
> fix: uses the body of the comment

- .github/workflows/comment-triggers.yml
> fix: trigger check for comment commands

- .github/workflows/comment-triggers.yml
- .github/workflows/mythx-changed.yml
- .github/workflows/mythx-full.yml
> fix: improves security in workflows

- .github/workflows/mythx-changed.yml
- .github/workflows/mythx-full.yml
> fix: adjust workflow jobs permissions

- .github/workflows/documentation-update.yml
Adds a new github actions workflow to update the smart contract documentation in aragon/builders-portal.
By definition it opens a new pull request and assigns the person that triggers the workflow as a reviewer.
Task: DOPS-319
> feat: adds workflow to automatically update docs in aragon/builders-portal

- .github/workflows/documentation-update.yml
Adds the DevRel team as reviewers for pull requests to update docs in aragon/builders-portal
Task: DOPS-319
> feat: adds devrel team to review doc pull request

- packages/contracts/CHANGELOG.md
- packages/contracts/deploy/30_repo-factory.ts
- packages/contracts/deploy/60_dao-factory.ts
- packages/contracts/deploy/70_permissions.ts
- packages/contracts/hardhat.config.ts
- packages/contracts/networks.json
- packages/subgraph/CHANGELOG.md
- packages/subgraph/schema.graphql
Bundles the permission granting during deployment into 1 file.
Fixes goerli network configuration
removes subgraph not null enforcing on Proposal.metadata
> Fixes Contract deployment and permission granting

- .github/workflows/subgraph-deploy.yaml
> DOPS-351 Added toJson() to fix error in subgraph-deploy workflow

- packages/contracts/CHANGELOG.md
- packages/contracts/contracts/core/DAO.sol
- packages/contracts/contracts/core/IDAO.sol
- packages/contracts/contracts/core/component/CallbackHandler.sol
- packages/contracts/contracts/core/component/Component.sol
- packages/contracts/contracts/core/component/MetaTxComponent.sol
- packages/contracts/contracts/registry/InterfaceBasedRegistry.sol
- packages/contracts/contracts/registry/ens/ENSSubdomainRegistrar.sol
- packages/contracts/contracts/test/CallbackHandlerHelperMock.sol
- packages/contracts/contracts/test/CallbackHandlerMock.sol
- packages/contracts/contracts/test/DAOMock.sol
- packages/contracts/contracts/tokens/MerkleDistributor.sol
- packages/contracts/contracts/tokens/MerkleMinter.sol
- packages/contracts/contracts/voting/allowlist/AllowlistVoting.sol
- packages/contracts/contracts/voting/erc20/ERC20Voting.sol
- packages/contracts/contracts/voting/majority/MajorityVotingBase.sol
- packages/contracts/test/core/component/callback-handler.ts
- packages/contracts/test/plugin/plugin-repo.ts
- packages/contracts/test/registry/interface-based-registry.ts
Applied changes to the PR after review and discussions with @novaknole.
Task: [associated with APP-955](https://aragonassociation.atlassian.net/browse/APP-955)
> Refactored AdaptiveERC165 into independent CallbackHandler

- packages/contracts/contracts/voting/allowlist/AllowlistVotingSetup.sol
- packages/contracts/contracts/voting/erc20/ERC20VotingSetup.sol
- packages/contracts/test/voting/allowlist-voting-setup.ts
- packages/contracts/test/voting/erc20-voting-setup.ts
- Test AllowlistVotingSetup.
- Test ERC20VotingSetup.
Task: [APP-903](https://aragonassociation.atlassian.net/browse/APP-903)
> APP-903  test AllowlistVotingSetup and ERC20VotingSetup

- .github/workflows/subgraph-tests.yml
- packages/subgraph/CHANGELOG.md
- packages/subgraph/manifest/subgraph.placeholder.yaml
- packages/subgraph/schema.graphql
- packages/subgraph/src/dao/dao.ts
- packages/subgraph/tests/allowlist-voting/allowlist-voting.test.ts
- packages/subgraph/tests/dao/dao.test.ts
- packages/subgraph/tests/dao/utils.ts
- packages/subgraph/tests/erc20-voting/erc20-voting.test.ts
- packages/subgraph/tests/utils.ts
Adds missing events from `contracts/core` to the subgraph.
Task: APP-1134
> App 1134 subgraph adapt events to work with the new core

- .github/workflows/contracts-deploy.yml
> fix: contract deploy workflow

- .github/helpers/contracts/register-ens.js
- .github/workflows/contracts-deploy.yml
runs contracts deploy also on changes in helpers
Task: [ID]()
> fix: random ens registration script

- packages/contracts-ethers/CHANGELOG.md
- packages/contracts-ethers/package.json
- packages/contracts/CHANGELOG.md
- packages/contracts/package.json
> feat: update changelogs because the action failed

- .github/helpers/contracts/prepare.js
- .github/helpers/subgraph/buildMatrix.js
> fix: github output handling in js files

- packages/contracts/CHANGELOG.md
- packages/contracts/contracts/test/MajorityVotingMock.sol
- packages/contracts/contracts/voting/allowlist/AllowlistVoting.sol
- packages/contracts/contracts/voting/allowlist/AllowlistVotingSetup.sol
- packages/contracts/contracts/voting/erc20/ERC20Voting.sol
- packages/contracts/contracts/voting/erc20/ERC20VotingSetup.sol
- packages/contracts/contracts/voting/majority/IMajorityVoting.sol
- packages/contracts/contracts/voting/majority/MajorityVotingBase.sol
- packages/contracts/test/core/dao.ts
- packages/contracts/test/test-utils/voting.ts
- packages/contracts/test/voting/allowlist-voting-setup.ts
- packages/contracts/test/voting/allowlist-voting.ts
- packages/contracts/test/voting/erc20-voting-setup.ts
- packages/contracts/test/voting/erc20-voting.ts
- packages/contracts/test/voting/majority-voting.ts
- packages/contracts/utils/event.ts
- packages/subgraph/schema.graphql
- packages/subgraph/src/dao/utils.ts
- packages/subgraph/src/packages/allowlist/allowlist-voting.ts
- packages/subgraph/src/packages/erc20/erc20-voting.ts
- packages/subgraph/tests/allowlist-voting/allowlist-voting.test.ts
- packages/subgraph/tests/allowlist-voting/utils.ts
- packages/subgraph/tests/dao/utils.ts
- packages/subgraph/tests/erc20-voting/erc20-voting.test.ts
- packages/subgraph/tests/erc20-voting/utils.ts
- packages/subgraph/tests/utils.ts
The current execution logic could lead to unexpected and unintuitive vote ends for certain parameter settings.
This PR fixes and clarifies the execution logic by replacing the quantity 
$$\text{participation} = (N_\text{yes} + N_\text{no} + N_\text{abstain})/N_\text{total}$$
by 
$$\text{total support} = N_\text{yes} / N_\text{total}$$ 
as this was done in client.
The other quantity used for checking if the vote is passed,
$$\text{relative support} = N_\text{yes} / (N_\text{yes} + N_\text{no})$$
remains untouched.
In particular, early execution should be only allowed iff (if and only if) the vote outcome cannot change anymore ( $\text{total support} > \text{relative support threshold}$ assuming that is chosen with $\text{relative support threshold} > 50%$).
We also prevent the vote creator …
> Fix and clarify the MajorityVoting execution logic

- packages/subgraph/schema.graphql
- packages/subgraph/src/packages/addresslist/addresslist-voting.ts
- packages/subgraph/src/packages/token/token-voting.ts
- packages/subgraph/tests/addresslist-voting/addresslist-voting.test.ts
- packages/subgraph/tests/addresslist-voting/utils.ts
- packages/subgraph/tests/token-voting/token-voting.test.ts
- packages/subgraph/tests/token-voting/utils.ts
Adds new data to the subgraph that are requested by the app team
Task: APP-1140
> feat: adds new data to proposals

- packages/contracts/contracts/voting/addresslist/AddresslistVoting.sol
- packages/contracts/contracts/voting/majority/MajorityVotingBase.sol
- packages/contracts/contracts/voting/token/TokenVoting.sol
- packages/contracts/test/test-utils/voting.ts
- packages/contracts/test/voting/addresslist-voting-setup.ts
- packages/contracts/test/voting/addresslist-voting.ts
- packages/contracts/test/voting/majority-voting.ts
- packages/contracts/test/voting/token-voting-setup.ts
- packages/contracts/test/voting/token-voting.ts
This PR applies https://github.com/aragon/core/pull/157 to the `develop` branch
Task: [APP-1384](https://aragonassociation.atlassian.net/browse/APP-1384)
> Apply HAL-03 and HAL-04 to `develop`

- packages/subgraph/schema.graphql
> fix: marks subgraph action entity as mutable

- packages/subgraph/src/packages/addresslist/addresslist-voting.ts
- packages/subgraph/src/packages/token/token-voting.ts
> Bug/Fix vote: assign correct voter id

- packages/contracts/test/plugin/plugin-setup-processor.ts
> add extra check for upgradeability test

- packages/contracts/contracts/voting/majority/MajorityVotingBase.sol
- packages/contracts/contracts/voting/multisig/Multisig.sol
Per discussion, we decided:
* The MajorityVotingBase and AddressList should be usable by anyone and should be highly modifyable. So making all functions virtual.
* The most inheritted contracts of plugins such as MultiSig, TokenVoting, AddressListVoting, they don't necessarily be inheritted (or we will discuss this again once more in the future).
Task: [ID]()
> make it virtual

- packages/subgraph/CHANGELOG.md
- packages/subgraph/src/utils/constants.ts
> fix: updates MULTISIG_INTERFACE in subgraph plugin detection

- packages/contracts/CHANGELOG.md
- packages/contracts/contracts/voting/multisig/Multisig.sol
- packages/contracts/hardhat.config.ts
- packages/contracts/test/test-utils/voting.ts
- packages/contracts/test/voting/multisig.ts
- packages/subgraph/CHANGELOG.md
- packages/subgraph/manifest/subgraph.placeholder.yaml
- packages/subgraph/schema.graphql
- packages/subgraph/src/packages/multisig/multisig.ts
- packages/subgraph/tests/multisig/multisig.test.ts
- packages/subgraph/tests/multisig/utils.ts
removes open and executable fields from Multisig proposals
- Removes `open` field from mutlisig proposals
- Adds `startDate` and `endDate` to mutlisig proposals
Task: APP-1430
> feat: adds start and enddate to multisig proposals

- packages/contracts/contracts/voting/multisig/Multisig.sol
- packages/contracts/test/test-utils/voting.ts
- packages/contracts/test/voting/multisig.ts
- Fixes for pull #187 
Task: [ID]()
> Fixes for pull #187

- packages/subgraph/CHANGELOG.md
- packages/subgraph/package.json
- packages/subgraph/src/utils/constants.ts
Fixes outdated interfaces in subgraph
Task: [ID]()
> fix: updates interfaces used by subgraph for plugin detection

- packages/contracts/contracts/plugin/PluginSetup.sol
- packages/contracts/contracts/plugin/examples/count/CounterV1PluginSetup.sol
- packages/contracts/contracts/plugin/examples/count/CounterV2PluginSetup.sol
> remove duplication

- packages/contracts/CHANGELOG.md
- packages/contracts/contracts/core/permission/PermissionLib.sol
- packages/contracts/contracts/core/permission/PermissionManager.sol
- packages/contracts/contracts/test/PermissionManagerTest.sol
- packages/contracts/docs/core/01-how-it-works/01-the-core-contracts/02-permissions.md
- packages/contracts/docs/core/01-how-it-works/02-the-dao-framework/02-plugin-repository/04-plugin-setup.md
- packages/contracts/test/core/permission/permission-manager.ts
- packages/subgraph/manifest/subgraph.placeholder.yaml
- packages/subgraph/schema.graphql
- packages/subgraph/src/dao/dao.ts
- packages/subgraph/tests/dao/permission-manager.test.ts
- packages/subgraph/tests/dao/utils.ts
Completely `removes` freeze functionality.  The last chance to give it the last thought whether we're ready to remove this feature...
Task: [ID]()
> remove freeze

- packages/contracts/contracts/voting/multisig/Multisig.sol
- packages/contracts/test/voting/multisig.ts
> remove shadowing

- .gitignore
- .prettierrc
- .vscode/settings.json
- packages/contracts/package.json
- packages/subgraph/package.json
- yarn.lock
fix: fixes repo workspace settings
feat: adds formatting commands to subgraph and contracts
Replaces #201 
Task: [ID]()
> fix: fixes repo workspace settings

- packages/contracts/CHANGELOG.md
- packages/contracts/contracts/core/plugin/ProposalBase.sol
- packages/contracts/contracts/voting/admin/Admin.sol
- packages/contracts/contracts/voting/majority/MajorityVotingBase.sol
- packages/contracts/contracts/voting/multisig/Multisig.sol
feat: removes EIP-165 implementation from ProposalBase
Task: APP-1582
> feat: removes EIP-165 implementation from ProposalBase

- packages/contracts/CHANGELOG.md
- packages/contracts/contracts/core/permission/PermissionLib.sol
- packages/contracts/contracts/core/permission/PermissionManager.sol
- packages/contracts/contracts/factory/DAOFactory.sol
- packages/contracts/contracts/factory/PluginRepoFactory.sol
- packages/contracts/contracts/plugin/IPluginSetup.sol
- packages/contracts/contracts/plugin/PluginSetup.sol
- packages/contracts/contracts/plugin/PluginSetupProcessor.sol
- packages/contracts/contracts/plugin/examples/count/CounterV1PluginSetup.sol
- packages/contracts/contracts/plugin/examples/count/CounterV2PluginSetup.sol
- packages/contracts/contracts/test/plugin-mock/Clonable/PluginCloneableSetupMock.sol
- packages/contracts/contracts/test/plugin-mock/PluginMockData.sol
- packages/contracts/contracts/test/plugin-mock/UUPSUpgradeable/PluginUUPSUpgradeableSetupMock.sol
- packages/contracts/contracts/voting/addresslist/AddresslistVotingSetup.sol
- packages/contracts/contracts/voting/admin/AdminSetup.sol
- packages/contracts/contracts/voting/multisig/MultisigSetup.sol
- packages/contracts/contracts/voting/token/TokenVotingSetup.sol
- packages/contracts/test/core/permission/permission-manager.ts
feat: renames ItemSingleTarget to SingleTargetPermission
feat: renames ItemMultiTarget to MultiTargetPermission
feat: renames bulkOnSingleTarget to applySingleTargetPermissions
feat: renames bulkOnMultiTarget to applyMultiTargetPermissions
Task: [ID]()
> feat: renames ItemSingleTarget to SingleTargetPermission

- packages/contracts/contracts/core/plugin/Plugin.sol
- packages/contracts/contracts/core/plugin/PluginCloneable.sol
- packages/contracts/contracts/core/plugin/PluginUUPSUpgradeable.sol
> fix inheritance chain

- CONTRIBUTION_GUIDE.md
This is the Contribution Guide for open source developers who come in and want to contribute to our codebase.
Task: [ID]()
I added a `CONTRIBUTION_GUIDE.md` doc detailing steps to follow for devs coming in.
- [n/a] I have commented my code, particularly in hard-to-understand areas.
- [n/a] Any dependent changes have been merged and published in downstream modules.
- [n/a] I ran all tests with success and extended them if necessary.
- [n/a] I have updated the ``CHANGELOG.md`` file in the root folder.
- [n/a] I have tested my code on the test network.
> Contribution Guide

- packages/subgraph/CHANGELOG.md
- packages/subgraph/schema.graphql
- packages/subgraph/src/packages/addresslist/addresslist-voting.ts
- packages/subgraph/src/packages/token/token-voting.ts
- packages/subgraph/tests/addresslist-voting/addresslist-voting.test.ts
- packages/subgraph/tests/token-voting/token-voting.test.ts
Added `voteReplaced` and `updatedAt` to `TokenVotingVote` and `AddresslistVotingVote`.
Task: [APP-1662](https://aragonassociation.atlassian.net/browse/APP-1662)
[APP-1662]: https://aragonassociation.atlassian.net/browse/APP-1662?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> APP-1662: add voteReplaced

- .github/helpers/contracts/register-ens-subdomain.js
- .github/workflows/contract-tests.yml
- .github/workflows/contracts-deploy.yml
- packages/contracts/CHANGELOG.md
- packages/contracts/contracts/factory/PluginRepoFactory.sol
- packages/contracts/contracts/registry/DAORegistry.sol
- packages/contracts/contracts/registry/PluginRepoRegistry.sol
- packages/contracts/contracts/registry/RegistryUtils.sol
- packages/contracts/contracts/test/RegistryUtils.sol
- packages/contracts/deploy/10_framework/00_ens.ts
- packages/contracts/deploy/30_plugins/10_plugin-repos/00_create-plugins-repo.ts
- packages/contracts/test/factory/dao-factory.ts
- packages/contracts/test/factory/plugin-repo-factory.ts
- packages/contracts/test/plugin/plugin-setup-processor.ts
- packages/contracts/test/registry/dao-registry.ts
- packages/contracts/test/registry/plugin-repo-registry.ts
- packages/contracts/test/registry/registry-utils.ts
- packages/contracts/utils/ens.ts
- packages/subgraph/CHANGELOG.md
- packages/subgraph/schema.graphql
- packages/subgraph/src/registries/daoRegistry.ts
- packages/subgraph/src/registries/pluginRepoRegistry.ts
- packages/subgraph/tests/registry/daoRegistry.test.ts
- packages/subgraph/tests/registry/pluginRepoRegistry.test.ts
feat: adds check that plugin or dao name only contains a limited charset
Task: APP-1545
> feat: adds check that plugin or dao name only contains a limited charset

- packages/subgraph/CHANGELOG.md
- packages/subgraph/schema.graphql
- packages/subgraph/src/packages/addresslist/addresslist-voting.ts
- packages/subgraph/src/packages/admin/admin.ts
- packages/subgraph/src/packages/multisig/multisig.ts
- packages/subgraph/src/packages/token/token-voting.ts
- packages/subgraph/tests/addresslist-voting/addresslist-voting.test.ts
- packages/subgraph/tests/admin/admin.test.ts
- packages/subgraph/tests/multisig/multisig.test.ts
- packages/subgraph/tests/token-voting/token-voting.test.ts
Task: [APP-1534](https://aragonassociation.atlassian.net/browse/APP-1534)
[APP-1534]: https://aragonassociation.atlassian.net/browse/APP-1534?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> add execution tx hash to proposal entity

- packages/contracts/contracts/registry/DAORegistry.sol
- packages/contracts/contracts/registry/ens/ENSSubdomainRegistrar.sol
- packages/contracts/test/registry/dao-registry.ts
- packages/contracts/test/registry/plugin-repo-registry.ts
> state vars public

- packages/contracts/contracts/plugin/PluginSetupProcessor.sol
feat: makes PSP state public for future versions to use
Task: APP-1606
> feat: makes PSP state public for future versions to use

- packages/contracts/contracts/factory/PluginRepoFactory.sol
- packages/contracts/contracts/factory/TokenFactory.sol
- packages/contracts/contracts/plugin/PluginRepo.sol
- packages/contracts/contracts/registry/InterfaceBasedRegistry.sol
- packages/contracts/contracts/test/plugin-mock/UUPSUpgradeable/PluginUUPSUpgradeableSetupMock.sol
- packages/contracts/contracts/voting/multisig/Multisig.sol
> remove todo

- .github/workflows/contract-tests.yml
- packages/contracts/src/token/ERC20/governance/GovernanceERC20.sol
- packages/subgraph/CHANGELOG.md
- packages/subgraph/manifest/subgraph.placeholder.yaml
- packages/subgraph/package.json
- packages/subgraph/schema.graphql
- packages/subgraph/src/packages/admin/admin.ts
- packages/subgraph/src/packages/admin/adminMembers.ts
- packages/subgraph/tests/admin/admin.test.ts
- packages/subgraph/tests/admin/adminMembers.test.ts
- packages/subgraph/tests/admin/utils.ts
Subgraph changes:
- fixes typo in administrator
- adds back administrator by handling the new events
Task: [ID]()
> App 1385 subgraph update to use the new plugin parameters

- packages/contracts/test/core/dao/dao.ts
- packages/contracts/test/core/plugin/shared-plugin.ts
- packages/contracts/test/plugins/governance/admin/admin-setup.ts
- packages/contracts/test/plugins/governance/majority-voting/addresslist/addresslist-voting.ts
- packages/contracts/test/plugins/governance/majority-voting/token/token-voting.ts
- packages/contracts/test/plugins/governance/multisig/multisig-setup.ts
- packages/contracts/test/plugins/governance/multisig/multisig.ts
- packages/contracts/test/plugins/utils/ratio.ts
> fix await for staticcall revert

- packages/contracts/docs/core/01-how-it-works/02-framework/03-ens-names.md
- packages/contracts/docs/core/03-reference-guide/index.md
- packages/contracts/docs/core/index.md
> Docs: Fixes for the ENS section

- packages/contracts/docs/core/01-how-it-works/01-core/01-dao/01-actions.md
- packages/contracts/docs/core/01-how-it-works/01-core/index.md
- packages/contracts/docs/core/01-how-it-works/02-framework/index.md
- packages/contracts/docs/core/02-how-to-guides/01-plugin-development/01-implemention/01-plugin-types.md
- packages/contracts/docs/core/02-how-to-guides/01-plugin-development/01-implemention/02-non-upgradeable-contracts.md
- packages/contracts/docs/core/02-how-to-guides/01-plugin-development/03-publication/index.md
> Fix: typos

- .prettierrc
- packages/contracts/.prettierignore
- packages/contracts/README.md
- packages/contracts/docs/core/01-how-it-works/01-core/02-permissions/01-conditions.md
- packages/contracts/docs/core/02-how-to-guides/01-plugin-development/01-implemention/02-non-upgradeable-contracts.md
- packages/contracts/docs/core/02-how-to-guides/01-plugin-development/01-implemention/03-upgradeable-contracts.md
- packages/contracts/package.json
Includes markdown files in the`yarn formatting:check` and `yarn formatting:write` scripts
> Include .md files in the formatting check

- packages/contracts/src/core/plugin/proposal/IProposal.sol
- packages/contracts/src/core/plugin/proposal/Proposal.sol
- packages/contracts/src/core/plugin/proposal/ProposalUpgradeable.sol
- packages/contracts/test/plugins/governance/admin/admin.ts
- packages/subgraph/manifest/subgraph.placeholder.yaml
- packages/subgraph/src/packages/addresslist/addresslist-voting.ts
- packages/subgraph/src/packages/admin/admin.ts
- packages/subgraph/src/packages/multisig/multisig.ts
- packages/subgraph/src/packages/token/token-voting.ts
- packages/subgraph/tests/addresslist-voting/utils.ts
- packages/subgraph/tests/admin/admin.test.ts
- packages/subgraph/tests/admin/utils.ts
- packages/subgraph/tests/multisig/utils.ts
- packages/subgraph/tests/token-voting/utils.ts
> remove execresult

- packages/contracts/CHANGELOG.md
- packages/contracts/deploy/10_framework/40_plugin_setup_processor.ts
- packages/contracts/deploy/10_framework/99_verifiy_step.ts
- packages/contracts/src/framework/plugin/setup/PluginSetupProcessor.sol
- packages/contracts/test/framework/dao/dao-factory.ts
- packages/contracts/test/framework/plugin/plugin-setup-processor.ts
- packages/contracts/test/test-utils/plugin-setup-processor.ts
> Removed redundant `DaoAuthorizable` dependency from `PluginSetupProcessor`

- .github/workflows/subgraph-deploy.yaml
> fix: subgraph deployment

- packages/contracts/src/core/permission/PermissionManager.sol
> make pm virtual/abstract

- packages/contracts/src/framework/plugin/repo/PluginRepoFactory.sol
- packages/contracts/src/plugins/governance/admin/AdminSetup.sol
> Fix natspec

- packages/contracts/src/framework/plugin/repo/PluginRepo.sol
- packages/contracts/src/framework/plugin/repo/PluginRepoFactory.sol
- packages/contracts/test/framework/plugin/plugin-repo-factory.ts
- packages/contracts/test/framework/plugin/plugin-repo.ts
> Feature/plugin repo tests+fix

- packages/contracts/CHANGELOG.md
- packages/contracts/deploy/99_conclude/10_verify-contracts.ts
- packages/contracts/src/core/plugin/PluginUUPSUpgradeable.sol
- packages/contracts/src/framework/plugin/setup/IPluginSetup.sol
- packages/contracts/src/framework/plugin/setup/PluginSetupProcessor.sol
- packages/contracts/src/plugins/counter-example/v1/CounterV1PluginSetup.sol
- packages/contracts/src/plugins/counter-example/v2/CounterV2PluginSetup.sol
- packages/contracts/src/plugins/governance/admin/AdminSetup.sol
- packages/contracts/src/plugins/governance/majority-voting/addresslist/AddresslistVotingSetup.sol
- packages/contracts/src/plugins/governance/majority-voting/token/TokenVotingSetup.sol
- packages/contracts/src/plugins/governance/multisig/MultisigSetup.sol
- packages/contracts/src/test/plugin/Clonable/PluginCloneableSetupMock.sol
- packages/contracts/src/test/plugin/UUPSUpgradeable/PluginUUPSUpgradeableSetupMock.sol
- packages/contracts/test/framework/plugin/plugin-setup-processor.ts
- packages/contracts/test/plugins/counter-example/counter-plugin-setup.ts
- packages/contracts/test/plugins/governance/admin/admin-setup.ts
- packages/contracts/test/plugins/governance/majority-voting/addresslist/addresslist-voting-setup.ts
- packages/contracts/test/plugins/governance/majority-voting/token/token-voting-setup.ts
- packages/contracts/test/plugins/governance/multisig/multisig-setup.ts
Renamed `getImplementationAddress` to `implementation` in `IPluginSetup`
> Renamed `getImplementationAddress` to `implementation` in `IPluginSetup`

- packages/subgraph/CHANGELOG.md
- packages/subgraph/schema.graphql
- packages/subgraph/src/packages/multisig/multisig.ts
- packages/subgraph/src/utils/constants.ts
- packages/subgraph/tests/multisig/multisig.test.ts
- packages/subgraph/tests/multisig/utils.ts
Task: [APP-1832](https://aragonassociation.atlassian.net/browse/APP-1832)
[APP-1832]: https://aragonassociation.atlassian.net/browse/APP-1832?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> APP-1832 : implement executable into MultisigProposal

- .github/workflows/contract-tests.yml
- packages/contracts/deploy/00_managing-dao/99_verify_step.ts
- packages/contracts/deploy/20_permissions/00_ens-permissions.ts
- packages/contracts/deploy/20_permissions/10_dao-registry-permissions.ts
- packages/contracts/deploy/20_permissions/20_plugin-registrty-permissions.ts
- packages/contracts/deploy/40_finalize-managing-dao/30_install-multisig-on-managing-dao.ts
- packages/contracts/hardhat.config.ts
- packages/contracts/test/deploy/managing-dao.ts
- packages/contracts/utils/types.ts
Test ManagingDAO, and check if it can upgrade the framework
Task: [APP-1793](https://aragonassociation.atlassian.net/browse/APP-1793)
[APP-1793]: https://aragonassociation.atlassian.net/browse/APP-1793?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> APP-1793 test framework deployment

- packages/contracts/deploy/00_managing-dao/01_managing-dao_conclude.ts
- packages/contracts/deploy/00_managing-dao/20_set-dao-permission.ts
- packages/contracts/deploy/10_framework/00_ens.ts
- packages/contracts/deploy/10_framework/01_ens_conclude.ts
- packages/contracts/deploy/10_framework/11_dao-registry_conclude.ts
- packages/contracts/deploy/10_framework/21_plugin-repo-registry_conclude.ts
- packages/contracts/deploy/10_framework/31_repo-factory_conclude.ts
- packages/contracts/deploy/10_framework/41_plugin-setup-processor_conclude.ts
- packages/contracts/deploy/10_framework/51_dao-factory-conclude.ts
- packages/contracts/deploy/30_plugins/00_plugin-setups/01_addresslist_voting_setup_conclude.ts
- packages/contracts/deploy/30_plugins/00_plugin-setups/11_token_voting_setup_conclude.ts
- packages/contracts/deploy/30_plugins/00_plugin-setups/21_admin_setup_conclude.ts
- packages/contracts/deploy/30_plugins/00_plugin-setups/31_multisig_setup_conclude.ts
- packages/contracts/deploy/30_plugins/10_plugin-repos/01_create-plugins-repo_conclude.ts
- packages/contracts/deploy/40_finalize-managing-dao/30_install-multisig-on-managing-dao.ts
- packages/contracts/deploy/99_conclude/10_verify-contracts.ts
- packages/contracts/deploy/helpers.ts
- packages/contracts/hardhat.config.ts
- packages/contracts/test/test-utils/ens.ts
- packages/contracts/tsconfig.json
- packages/contracts/utils/ens.ts
- packages/contracts/utils/etherscan.ts
- packages/contracts/utils/types.ts
> feat: verify all deployed contracts

- packages/contracts/src/plugins/utils/Ratio.sol
- packages/contracts/src/test/utils/RatioTest.sol
- packages/contracts/test/plugins/utils/ratio.ts
Task: [APP-1908](https://aragonassociation.atlassian.net/browse/APP-1908)
[APP-1908]: https://aragonassociation.atlassian.net/browse/APP-1908?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Removed unused function `_applyRatioFloored`

- packages/contracts/src/framework/plugin/repo/PluginRepoFactory.sol
- packages/contracts/src/framework/plugin/repo/PluginRepoRegistry.sol
- packages/contracts/src/framework/utils/RegistryUtils.sol
- packages/contracts/test/framework/plugin/plugin-repo-factory.ts
> move check

- packages/contracts/deploy/00_managing-dao/00_managing-dao.ts
- packages/contracts/deploy/helpers.ts
- packages/contracts/test/deploy/managing-dao.ts
> add metadata

- packages/contracts/test/core/dao/dao.ts
- packages/contracts/test/framework/plugin/plugin-setup-processor.ts
- packages/contracts/test/plugins/governance/admin/admin-setup.ts
- packages/contracts/test/plugins/governance/admin/admin.ts
- packages/contracts/test/plugins/governance/majority-voting/addresslist/addresslist-voting-setup.ts
- packages/contracts/test/plugins/governance/majority-voting/addresslist/addresslist-voting.ts
- packages/contracts/test/plugins/governance/majority-voting/majority-voting.ts
- packages/contracts/test/plugins/governance/majority-voting/token/token-voting-setup.ts
- packages/contracts/test/plugins/governance/majority-voting/token/token-voting.ts
- packages/contracts/test/plugins/governance/multisig/multisig-setup.ts
- packages/contracts/test/plugins/governance/multisig/multisig.ts
- packages/contracts/test/plugins/token/distribution/merkle-distributor.ts
- packages/contracts/test/plugins/token/distribution/merkle-minter.ts
- packages/contracts/test/token/erc20/governance-erc20.ts
- packages/contracts/test/token/erc20/governance-wrapped-erc20.ts
> from 0x00000000 to 0xffffffff for interface check

- packages/contracts/docs/osx/01-how-it-works/01-core/01-dao/01-actions.md
- packages/contracts/docs/osx/01-how-it-works/01-core/02-permissions/01-conditions.md
- packages/contracts/docs/osx/01-how-it-works/01-core/02-permissions/index.md
- packages/contracts/docs/osx/02-how-to-guides/02-plugin-development/03-non-upgradeable-plugin/01-initialization.md
- packages/contracts/docs/osx/02-how-to-guides/02-plugin-development/03-non-upgradeable-plugin/03-setup.md
- packages/contracts/docs/osx/02-how-to-guides/02-plugin-development/04-upgradeable-plugin/01-initialization.md
- packages/contracts/docs/osx/02-how-to-guides/02-plugin-development/04-upgradeable-plugin/02-implementation.md
- packages/contracts/docs/osx/02-how-to-guides/02-plugin-development/04-upgradeable-plugin/03-setup.md
- packages/contracts/docs/osx/02-how-to-guides/02-plugin-development/index.md
> Adapt docs to changed package name

- packages/contracts/docs/osx/01-how-it-works/02-framework/aragon-os-infrastructure-core-overview.drawio.svg
- packages/contracts/docs/osx/02-how-to-guides/01-dao/04-proposal-review.md
- packages/contracts/docs/osx/02-how-to-guides/02-plugin-development/05-governance-plugins/02-membership.md
- packages/contracts/docs/osx/index.md
Small improvements for the docs.
Documentation
> Docs: Various improvements

- DEPLOYMENT_CHECKLIST.md
- packages/contracts/docs/osx/01-how-it-works/01-core/01-dao/01-actions.md
- packages/contracts/docs/osx/01-how-it-works/01-core/02-permissions/01-conditions.md
- packages/contracts/docs/osx/01-how-it-works/01-core/02-permissions/index.md
- packages/contracts/docs/osx/02-how-to-guides/02-plugin-development/03-non-upgradeable-plugin/01-initialization.md
- packages/contracts/docs/osx/02-how-to-guides/02-plugin-development/03-non-upgradeable-plugin/03-setup.md
- packages/contracts/docs/osx/02-how-to-guides/02-plugin-development/04-upgradeable-plugin/01-initialization.md
- packages/contracts/docs/osx/02-how-to-guides/02-plugin-development/04-upgradeable-plugin/02-implementation.md
- packages/contracts/docs/osx/02-how-to-guides/02-plugin-development/04-upgradeable-plugin/03-setup.md
- packages/contracts/docs/osx/02-how-to-guides/02-plugin-development/index.md
- packages/contracts/docs/osx/index.md
- packages/contracts/src/README.md
- packages/contracts/src/package.json
feat: adds readme to said package
Task: [ID]()
> fix: rename osx-contracts to osx

- packages/contracts/docs/osx/01-how-it-works/02-framework/aragon-os-infrastructure-core-overview.drawio.svg
- packages/contracts/docs/osx/02-how-to-guides/02-plugin-development/03-non-upgradeable-plugin/03-setup.md
- packages/contracts/docs/osx/02-how-to-guides/02-plugin-development/04-upgradeable-plugin/03-setup.md
- packages/contracts/docs/osx/02-how-to-guides/02-plugin-development/index.md
- packages/contracts/docs/osx/index.md
> Docs: Improvements

- packages/subgraph/CHANGELOG.md
- packages/subgraph/package.json
- packages/subgraph/schema.graphql
- packages/subgraph/src/packages/multisig/multisig.ts
- packages/subgraph/tests/constants.ts
- packages/subgraph/tests/multisig/multisig.test.ts
- packages/subgraph/tests/multisig/utils.ts
- yarn.lock
Task: [APP-1935](https://aragonassociation.atlassian.net/browse/APP-1935)
[APP-1935]: https://aragonassociation.atlassian.net/browse/APP-1935?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> APP-1935 : Use int for minApprovals

- packages/contracts/.solcover.js
- packages/contracts/src/test/token/TestERC20.sol
- packages/contracts/test/core/dao/dao.ts
- packages/contracts/test/framework/utils/token-factory.ts
- packages/contracts/test/plugins/governance/majority-voting/addresslist/addresslist-voting.ts
- packages/contracts/test/plugins/governance/multisig/multisig.ts
- packages/contracts/test/plugins/token/distribution/merkle-distributor.ts
- packages/contracts/test/token/erc20/governance-wrapped-erc20.ts
This PR increases coverage from 82% to 97%.
There're some abstract contract tests missing, but we test them anyways in the derived ones.  Would be really unproductive to test them as unit tests just for the sake of 100% coverage.
Task: [ID]()
> coverage tests added

- packages/contracts/docs/osx/01-how-it-works/01-core/03-plugins/01-plugin-details.md
- packages/contracts/docs/osx/01-how-it-works/02-framework/02-plugin-management/01-plugin-repo/01-plugin-repo-creation.md
- packages/contracts/docs/osx/01-how-it-works/02-framework/02-plugin-management/01-plugin-repo/index.md
- packages/contracts/docs/osx/01-how-it-works/02-framework/02-plugin-management/01-plugin-repo/plugin-repo-overview.drawio.svg
- packages/contracts/docs/osx/01-how-it-works/02-framework/02-plugin-management/02-plugin-setup/01-security-risk-mitigation.md
- packages/contracts/docs/osx/01-how-it-works/02-framework/02-plugin-management/02-plugin-setup/plugin-installation.drawio.svg
- packages/contracts/docs/osx/01-how-it-works/02-framework/02-plugin-management/02-plugin-setup/plugin-uninstallation.drawio.svg
- packages/contracts/docs/osx/01-how-it-works/02-framework/02-plugin-management/02-plugin-setup/plugin-update.drawio.svg
- packages/contracts/docs/osx/01-how-it-works/02-framework/02-plugin-management/plugin-version.drawio.svg
- packages/contracts/docs/osx/01-how-it-works/02-framework/03-ens-names.md
- packages/contracts/docs/osx/02-how-to-guides/02-plugin-development/03-non-upgradeable-plugin/03-setup.md
- packages/contracts/docs/osx/02-how-to-guides/02-plugin-development/04-upgradeable-plugin/01-initialization.md
- packages/contracts/docs/osx/02-how-to-guides/02-plugin-development/04-upgradeable-plugin/02-implementation.md
- packages/contracts/docs/osx/02-how-to-guides/02-plugin-development/04-upgradeable-plugin/03-setup.md
- packages/contracts/docs/osx/02-how-to-guides/02-plugin-development/07-publication/01-publication-process.md
- packages/contracts/docs/osx/02-how-to-guides/02-plugin-development/07-publication/02-versioning.md
- packages/contracts/docs/osx/02-how-to-guides/index.md
- packages/contracts/src/framework/plugin/repo/PluginRepoFactory.sol
- packages/contracts/src/test/plugin/AdminCloneFactory.sol
Aggregated fixes for the osx docs
Documentation
> Documentation fixes

- packages/subgraph/CHANGELOG.md
- packages/subgraph/schema.graphql
> fix: makes Permissions in Subgraph mutable.

- packages/contracts/CHANGELOG.md
> fix: changelog merge fail

- packages/contracts/docs/osx/02-how-to-guides/02-plugin-development/03-non-upgradeable-plugin/03-setup.md
Fix the permission ID in the example mentioned in PR https://github.com/aragon/osx/pull/326.
Documentation
> Fix wrong permission id

- packages/contracts/docs/osx/02-how-to-guides/02-plugin-development/04-upgradeable-plugin/01-initialization.md
- packages/contracts/docs/osx/02-how-to-guides/02-plugin-development/04-upgradeable-plugin/03-setup.md
> Fix titles

- packages/subgraph/CHANGELOG.md
- packages/subgraph/schema.graphql
- packages/subgraph/src/packages/addresslist/addresslist-voting.ts
- packages/subgraph/src/packages/multisig/multisig.ts
- packages/subgraph/src/packages/token/token-voting.ts
- packages/subgraph/tests/addresslist-voting/addresslist-voting.test.ts
- packages/subgraph/tests/addresslist-voting/utils.ts
- packages/subgraph/tests/multisig/multisig.test.ts
- packages/subgraph/tests/multisig/utils.ts
- packages/subgraph/tests/token/token-voting.test.ts
- packages/subgraph/tests/token/utils.ts
Task: [OS-331](https://aragonassociation.atlassian.net/browse/OS-331)
[OS-331]: https://aragonassociation.atlassian.net/browse/OS-331?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OS-331 : Rename executable to potentiallyExecutable

- packages/subgraph/tests/dao/dao_v1_0_0.test.ts
- packages/subgraph/tests/helpers/method-classes.ts
Task: [OS-206](https://aragonassociation.atlassian.net/browse/OS-206)
[OS-206]: https://aragonassociation.atlassian.net/browse/OS-206?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OS-206: test dao with extended schema (part-1)

- packages/subgraph/CHANGELOG.md
- packages/subgraph/manifest/subgraph.placeholder.yaml
- packages/subgraph/schema.graphql
- packages/subgraph/src/dao/dao_v1_0_0.ts
- packages/subgraph/src/packages/multisig/multisig.ts
- packages/subgraph/src/packages/token/governance-erc20.ts
- packages/subgraph/src/plugin/pluginRepo.ts
- packages/subgraph/tests/dao/dao_v1_0_0.test.ts
- packages/subgraph/tests/helpers/method-classes.ts
- packages/subgraph/tests/plugin/pluginSetupProcessor.test.ts
- packages/subgraph/tests/token/governance-erc20.test.ts
- packages/subgraph/tests/token/token-voting.test.ts
- packages/subgraph/tests/token/utils.ts
Task: [OS-365](https://aragonassociation.atlassian.net/browse/OS-365)
[OS-365]: https://aragonassociation.atlassian.net/browse/OS-365?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OS-365 : map and test delegation

- packages/contracts/CHANGELOG.md
Add missing changelog entries for the OSX contracts for commit 527474bb14529f2892e8277f6d7a1ca2da637a55
Task: [None]()
- changelog fix
> Add missing changelog entry

- packages/contracts/CHANGELOG.md
- packages/contracts/src/plugins/governance/majority-voting/addresslist/AddresslistVoting.sol
- packages/contracts/src/plugins/governance/majority-voting/token/TokenVoting.sol
- packages/contracts/src/plugins/governance/multisig/Multisig.sol
- packages/contracts/test/plugins/governance/majority-voting/addresslist/addresslist-voting.ts
- packages/contracts/test/plugins/governance/majority-voting/token/token-voting.ts
- packages/contracts/test/plugins/governance/multisig/multisig.ts
Task: [OS-389](https://aragonassociation.atlassian.net/browse/OS-389)
[OS-389]: https://aragonassociation.atlassian.net/browse/OS-389?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Feature/os 389 Membership definition update

- packages/subgraph/CHANGELOG.md
- packages/subgraph/manifest/subgraph.placeholder.yaml
- packages/subgraph/schema.graphql
- packages/subgraph/src/dao/dao_v1_0_0.ts
- packages/subgraph/tests/dao/dao_v1_0_0.test.ts
- packages/subgraph/tests/dao/utils.ts
- packages/subgraph/tests/helpers/method-classes.ts
Task: [OS-203](https://aragonassociation.atlassian.net/browse/OS-203)
[OS-203]: https://aragonassociation.atlassian.net/browse/OS-203?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OS-203 : index DAO URI

- packages/contracts/networks.json
updates infura keys used in networks.json to be all the same and aligned with the frontend
Task: [ID]()
> feat: updates infura keys used

- .github/workflows/contract-tests.yml
- .github/workflows/documentation-update.yml
- packages/contracts-versions/package.json
- packages/contracts/package.json
Task: [OS-435](https://aragonassociation.atlassian.net/browse/OS-435)
[OS-435]: https://aragonassociation.atlassian.net/browse/OS-435?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix documentation generation workflow

- packages/subgraph/src/packages/token/governance-erc20.ts
- packages/subgraph/tests/token/governance-erc20.test.ts
Task: [OS-418](https://aragonassociation.atlassian.net/browse/OS-418)
[OS-418]: https://aragonassociation.atlassian.net/browse/OS-418?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Feature: Update membership definition

- packages/subgraph/CHANGELOG.md
- packages/subgraph/schema.graphql
Task: [OS-437](https://aragonassociation.atlassian.net/browse/OS-437)
[OS-437]: https://aragonassociation.atlassian.net/browse/OS-437?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OS-437 : swap IPlugin for PluginInstallation on DAO entity

- packages/contracts/deploy/update/to_v1.3.0/99_ManagingDAO.ts
> fix: add initializeFrom call to the managing DAO proposal

- packages/contracts/docs/osx/01-how-it-works/02-framework/01-dao-creation/index.md
- packages/contracts/docs/osx/01-how-it-works/02-framework/02-plugin-management/01-plugin-repo/01-plugin-repo-creation.md
- packages/contracts/docs/osx/01-how-it-works/02-framework/03-ens-names.md
- packages/contracts/src/framework/dao/DAORegistry.sol
Task: [OS-504](https://aragonassociation.atlassian.net/browse/OS-504)
- documentation
[OS-504]: https://aragonassociation.atlassian.net/browse/OS-504?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Clarifying NatSpec comment in the `DAORegistry.register` function

- packages/contracts/src/framework/plugin/setup/PluginSetupProcessor.sol
Task: [OS-505](https://aragonassociation.atlassian.net/browse/OS-505)
- documentation
[OS-505]: https://aragonassociation.atlassian.net/browse/OS-505?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Improved NatSpec comment for `_canApply` in `PluginSetupProcessor`

- packages/contracts/CHANGELOG.md
- packages/contracts/src/core/permission/PermissionManager.sol
- packages/contracts/test/core/permission/permission-manager.ts
Applied Halborn code audit suggestion
Task: [OS-502](https://aragonassociation.atlassian.net/browse/OS-502)
[OS-502]: https://aragonassociation.atlassian.net/browse/OS-502?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Added revert case to applySingleTargetPermissions

- packages/contracts/CHANGELOG.md
- packages/contracts/src/core/permission/PermissionManager.sol
- packages/contracts/test/core/permission/permission-manager.ts
Task: [OS-503](https://aragonassociation.atlassian.net/browse/OS-503)
[OS-503]: https://aragonassociation.atlassian.net/browse/OS-503?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Added revert case to grantWithCondition

- packages/subgraph/package.json
- packages/subgraph/scripts/deploy-subgraph.sh
> bump package version

- packages/subgraph/manifest/data/polygon.json
Task: [OS-528](https://aragonassociation.atlassian.net/browse/OS-528)
[OS-528]: https://aragonassociation.atlassian.net/browse/OS-528?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix polygon manifest

- packages/contracts/CHANGELOG.md
- packages/contracts/src/framework/plugin/repo/PluginRepo.sol
- packages/contracts/src/framework/plugin/repo/PluginRepoFactory.sol
- packages/contracts/test/framework/dao/dao-factory.ts
- packages/contracts/test/framework/plugin/plugin-repo-factory.ts
- packages/contracts/test/framework/plugin/plugin-repo.ts
Task: [OS-525](https://aragonassociation.atlassian.net/browse/OS-525)
[OS-525]: https://aragonassociation.atlassian.net/browse/OS-525?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Added ProtocolVersion to PluginRepoFactory and PluginRepo

- packages/contracts/deploy/helpers.ts
- packages/contracts/deploy/update/to_v1.3.0/99_ManagingDAO.ts
Task: [OS-523](https://aragonassociation.atlassian.net/browse/OS-523)
[OS-523]: https://aragonassociation.atlassian.net/browse/OS-523?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OS-523 : add an extra check to deploy script

- packages/subgraph/package.json
- packages/subgraph/schema.graphql
- packages/subgraph/src/utils/tokens/erc20.ts
- packages/subgraph/tests/helpers/method-classes.ts
- packages/subgraph/tests/utils.ts
Adds missing field
https://app.satsuma.xyz/subgraphs/403/versions/2287
Task: [OS-530](https://aragonassociation.atlassian.net/browse/OS-530)
[OS-530]: https://aragonassociation.atlassian.net/browse/OS-530?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix: Add decimals to ERC20WrapperContract

- .github/workflows/documentation-update.yml
> feat(DOPS-541): renames builders-portal to develoer-portal

- README.md
Updated the Header's README so that it contains the links to our organization's information.
Task: [DX-37](https://aragonassociation.atlassian.net/browse/DX-37?atlOrigin=eyJpIjoiOGUxNjhiZmY1ZTgxNGRmZDk3NDU3NjA5YmNhYzUwMjAiLCJwIjoiaiJ9)
Documentation
[DX-37]: https://aragonassociation.atlassian.net/browse/DX-37?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update README Header

- packages/subgraph/manifest/subgraph.placeholder.yaml
Task: [OS-572](https://aragonassociation.atlassian.net/browse/OS-572)
[OS-572]: https://aragonassociation.atlassian.net/browse/OS-572?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OS-572 Add missing abis

- packages/contracts/docs/osx/02-how-to-guides/02-plugin-development/07-publication/02-metadata.md
Task: [OS-420](https://aragonassociation.atlassian.net/browse/OS-420)
- documentation
[OS-420]: https://aragonassociation.atlassian.net/browse/OS-420?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Metadata Format Specification in the Docs

- packages/contracts/CHANGELOG.md
Task: [ID]()
- documentation / changelog
> Fix: changelog entry

- packages/contracts/test/framework/plugin/plugin-repo.ts
- packages/contracts/test/test-utils/psp/hash-helpers.ts
> Move `tagHash` function

- packages/subgraph/CHANGELOG.md
- packages/subgraph/manifest/subgraph.placeholder.yaml
- packages/subgraph/package.json
Task: [OS-659](https://aragonassociation.atlassian.net/browse/OS-659)
[OS-659]: https://aragonassociation.atlassian.net/browse/OS-659?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> f/OS-659: Update Subgraph change log & version

- packages/subgraph/package.json
- packages/subgraph/tests/dao/dao_v1_3_0.test.ts
- yarn.lock
> chore: updates graph-cli to 0.52.0

- packages/subgraph/package.json
- packages/subgraph/tests/dao/dao_v1_3_0.test.ts
- yarn.lock
> fix(subgraph): update to @graphprotocol/graph-cli@0.52.0

- packages/contracts/docs/osx/02-how-to-guides/02-plugin-development/03-non-upgradeable-plugin/02-implementation.md
- packages/contracts/docs/osx/02-how-to-guides/02-plugin-development/03-non-upgradeable-plugin/03-setup.md
- packages/contracts/docs/osx/02-how-to-guides/02-plugin-development/04-upgradeable-plugin/02-implementation.md
- packages/contracts/docs/osx/02-how-to-guides/02-plugin-development/04-upgradeable-plugin/03-setup.md
- packages/contracts/docs/osx/02-how-to-guides/02-plugin-development/04-upgradeable-plugin/05-updating-versions.md
- packages/contracts/docs/osx/02-how-to-guides/02-plugin-development/index.md
Fixing index titles so they're read easier/faster within docs.
Task: [ID]()
Documentation
> changing the index titles

- packages/contracts-ethers/package.json
- packages/contracts/CHANGELOG.md
- packages/contracts/package.json
- packages/contracts/src/core/permission/IPermissionCondition.sol
- packages/contracts/src/core/permission/PermissionCondition.sol
- packages/contracts/src/core/permission/PermissionConditionUpgradeable.sol
- packages/contracts/src/package.json
- packages/subgraph/package.json
- packages/subgraph/tests/dao/dao_v1_3_0.test.ts
- yarn.lock
> chore: main to develop

- .github/workflows/subgraph-deploy.yaml
Task: [OS-529](https://aragonassociation.atlassian.net/browse/OS-529)
[OS-529]: https://aragonassociation.atlassian.net/browse/OS-529?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: allows subgraph deployment to be triggered manually

- packages/contracts/src/core/dao/DAO.sol
Task: [OS-718](https://aragonassociation.atlassian.net/browse/OS-718)
[OS-718]: https://aragonassociation.atlassian.net/browse/OS-718?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: revoke `SET_SIGNATURE_VALIDATOR_PERMISSION` that was granted to previous DAO versions

- packages/contracts/docs/developer-portal/02-how-to-guides/02-plugin-development/03-non-upgradeable-plugin/03-setup.md
- packages/contracts/docs/developer-portal/02-how-to-guides/02-plugin-development/03-non-upgradeable-plugin/index.md
- packages/contracts/docs/developer-portal/02-how-to-guides/02-plugin-development/04-upgradeable-plugin/03-setup.md
Task ID: [OS-178](https://aragonassociation.atlassian.net/browse/OS-178)
[OS-178]: https://aragonassociation.atlassian.net/browse/OS-178?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: corrected typo

- packages/subgraph/CHANGELOG.md
- packages/subgraph/manifest/subgraph.placeholder.yaml
- packages/subgraph/schema.graphql
- packages/subgraph/src/packages/token/token-voting.ts
- packages/subgraph/src/plugin/utils.ts
- packages/subgraph/src/utils/tokens/erc20.ts
- packages/subgraph/tests/dao/dao_v1_0_0.test.ts
- packages/subgraph/tests/dao/dao_v1_3_0.test.ts
QA: at https://subgraph.satsuma-prod.com/aragon/osx-baseGoerli/playground
query:
`
{
erc20Transfers {
id
token {
id
__typename
}
}
}
`
Task ID: [OS-771](https://aragonassociation.atlassian.net/browse/OS-771)
[OS-771]: https://aragonassociation.atlassian.net/browse/OS-771?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> bug / OS-771 : fix bug erc20 type collision

- packages/contracts/deploy/helpers.ts
Task ID: [OS-776](https://aragonassociation.atlassian.net/browse/OS-776)
[OS-776]: https://aragonassociation.atlassian.net/browse/OS-776?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: ipfs returned an empty string

- .vscode/extensions.json
- .vscode/settings.json
Apply the same code style settings as in https://github.com/aragon/osx-plugin-template-hardhat and https://github.com/aragon/osx-commons
- code style
> style: trailing comma

- packages/subgraph/package.json
> chore: bump subgraph version

- .github/workflows/subgraph-deploy.yaml
> fix(OS-798): uses arabot PAT to commit changelog

- packages/contracts/deploy/helpers.ts
PR https://github.com/aragon/osx/pull/485
> fix: empty metadata caused by IPFS upload returning an empty string

- packages/contracts/docs/developer-portal/04-framework-lifecycle/01-systems.md
- packages/contracts/docs/developer-portal/04-framework-lifecycle/03-osx-components/01-factory-contract.md
Fix the broken developer portal build: https://github.com/aragon/developer-portal/actions/runs/6611537954/job/17955616166?pr=132
- docs
> docs: fix broken dev portal build

- .github/workflows/subgraph-deploy.yaml
> ci(subgraph): fix condition for workflow dispatch

- packages/contracts/deploy/update/to_v1.3.0/10_DAOFactory.ts
- packages/contracts/deploy/update/to_v1.3.0/20_PluginRepoFactory.ts
- packages/contracts/deploy/update/to_v1.3.0/30_Multisig_PluginRepo.ts
- packages/contracts/deploy/update/to_v1.3.0/31_Multisig_Plugin.ts
- packages/contracts/deploy/update/to_v1.3.0/40_TokenVoting_PluginRepo.ts
- packages/contracts/deploy/update/to_v1.3.0/41_TokenVoting_Plugin.ts
- packages/contracts/deploy/update/to_v1.3.0/50_AddresslistVoting_PluginRepo.ts
- packages/contracts/deploy/update/to_v1.3.0/51_AddresslistVoting_Plugin.ts
- packages/contracts/deploy/update/to_v1.3.0/60_Admin_PluginRepo.ts
- packages/contracts/deploy/update/to_v1.3.0/90_ManagingDAO.ts
- packages/contracts/deploy/verification/99_conclude/01_managing_dao_proposal.ts
corrects managing DAO proposal formatting to be displayed properly by the UI
Task ID: [OS-927](https://aragonassociation.atlassian.net/browse/OS-927)
[OS-927]: https://aragonassociation.atlassian.net/browse/OS-927?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> deploy(contracts): corrects managing DAO proposal formatting

- .github/workflows/documentation-update.yml
- packages/contracts/.env.example
Excludes the plugin and token NatSpec docs from the developer-portal.
Task ID: [OS-1033](https://aragonassociation.atlassian.net/browse/OS-1033)
- doc generation workflow
[OS-1033]: https://aragonassociation.atlassian.net/browse/OS-1033?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ci: update doc generation workflow

- packages/contracts/docs/developer-portal/01-how-it-works/01-core/02-permissions/index.md
- packages/contracts/docs/developer-portal/01-how-it-works/02-framework/01-dao-creation/index.md
- packages/contracts/docs/developer-portal/01-how-it-works/02-framework/02-plugin-management/01-plugin-repo/01-plugin-repo-creation.md
- packages/contracts/docs/developer-portal/01-how-it-works/02-framework/02-plugin-management/01-plugin-repo/index.md
- packages/contracts/docs/developer-portal/01-how-it-works/02-framework/02-plugin-management/02-plugin-setup/01-security-risk-mitigation.md
- packages/contracts/docs/developer-portal/01-how-it-works/02-framework/03-ens-names.md
- packages/contracts/docs/developer-portal/02-how-to-guides/01-dao/02-action-execution.md
- packages/contracts/docs/developer-portal/02-how-to-guides/02-plugin-development/07-publication/02-metadata.md
Modified the links that appear in the .md documentation to adapt to Docusaurus v3 (and MDX v3).
Task ID: [OS-1070](https://aragonassociation.atlassian.net/browse/OS-1070)
[OS-1070]: https://aragonassociation.atlassian.net/browse/OS-1070?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: updated all links for consistence with docusaurus v3

- packages/contracts/docs/developer-portal/01-how-it-works/01-core/02-permissions/index.md
- packages/contracts/docs/developer-portal/01-how-it-works/02-framework/01-dao-creation/index.md
- packages/contracts/docs/developer-portal/01-how-it-works/02-framework/02-plugin-management/01-plugin-repo/01-plugin-repo-creation.md
- packages/contracts/docs/developer-portal/01-how-it-works/02-framework/02-plugin-management/01-plugin-repo/index.md
- packages/contracts/docs/developer-portal/01-how-it-works/02-framework/02-plugin-management/02-plugin-setup/01-security-risk-mitigation.md
- packages/contracts/docs/developer-portal/01-how-it-works/02-framework/03-ens-names.md
- packages/contracts/docs/developer-portal/02-how-to-guides/01-dao/02-action-execution.md
- packages/contracts/docs/developer-portal/02-how-to-guides/02-plugin-development/07-publication/02-metadata.md
This reverts commit 119fdb03128ee462723274410f532e5950aa447b obtained after squashing https://github.com/aragon/osx/pull/543.
> revert: "fix: updated all links for consistence with docusaurus v3"

- CONTRIBUTION_GUIDE.md
- packages/contracts/docs/developer-portal/02-how-to-guides/02-plugin-development/03-non-upgradeable-plugin/01-initialization.md
- packages/contracts/docs/developer-portal/02-how-to-guides/02-plugin-development/07-publication/index.md
- packages/contracts/docs/developer-portal/02-how-to-guides/02-plugin-development/index.md
- packages/contracts/docs/developer-portal/04-framework-lifecycle/04-sub-processes/01-protocol-version.md
Fixed all outdated GitHub links.
Task ID: [OS-1083](https://aragonassociation.atlassian.net/browse/OS-1083)
[OS-1083]: https://aragonassociation.atlassian.net/browse/OS-1083?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: replace old links for updated ones

- packages/subgraph/schema.graphql
Inline comments for schema.graphql.
These inline comments are meant to be displayed in the Aragon Developer Portal auto-generated documentation. Not to make the code more understandable.
Task ID: [OS-1080](https://aragonassociation.atlassian.net/browse/OS-1080)
[OS-1080]: https://aragonassociation.atlassian.net/browse/OS-1080?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ci: inline docs for Token and TokenBalance entities

- .github/workflows/subgraph-documentation-update.yml
- packages/contracts/docs/developer-portal/02-how-to-guides/01-dao/03-protocol-upgrades.md
- packages/subgraph/src/examples/01-query-examples/01-dao-query.ts
The action for updating subgraph documentation on Dev-Portal hasn't been triggered. This is because the job has the same name as in the file update_docs.yaml (for updating contracts documentation).
I also updated one query example so this PR can trigger the action.
Task ID: [OS-1198](https://aragonassociation.atlassian.net/browse/OS-1198)
[OS-1198]: https://aragonassociation.atlassian.net/browse/OS-1198?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix for Workflow update Subgraph Docs

- .github/pull_request_template.md
- .github/workflows/contract-tests.yml
- .github/workflows/subgraph-tests.yml
Changes addressed on this PR:
- Run actions over all PR relevant PR changes. 
- Run the actions over the commit changes made on main.
- Add `workflow_dispatch` to be able to run the action manually.
Task ID: [OS-1134](https://aragonassociation.atlassian.net/browse/OS-1134)
[OS-1134]: https://aragonassociation.atlassian.net/browse/OS-1134?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: update action work flow to run over pr changes 

- CONTRIBUTION_GUIDE.md
Task ID: [OS-1230](https://aragonassociation.atlassian.net/browse/OS-1230)
[OS-1230]: https://aragonassociation.atlassian.net/browse/OS-1230?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: update the security mail

- packages/contracts/src/framework/plugin/setup/PluginSetupProcessor.sol
Task ID: [OS-829](https://aragonassociation.atlassian.net/browse/OS-829)
- docs
[OS-829]: https://aragonassociation.atlassian.net/browse/OS-829?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: improve code comment in the `PluginSetupProcessor`

- packages/contracts/CHANGELOG.md
Update changelog 
Task ID: [OS-1299](https://aragonassociation.atlassian.net/browse/OS-1299)
[OS-1299]: https://aragonassociation.atlassian.net/browse/OS-1299?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(contracts): upddate changelog

- packages/contracts/src/package.json
> chore: bump contract dependencies

- packages/contracts/src/core/dao/DAO.sol
- packages/contracts/src/core/permission/PermissionManager.sol
- packages/contracts/src/core/utils/CallbackHandler.sol
- packages/contracts/src/framework/dao/DAOFactory.sol
- packages/contracts/src/framework/plugin/setup/PluginSetupProcessor.sol
- packages/contracts/src/framework/utils/InterfaceBasedRegistry.sol
- packages/contracts/test/core/dao/callback-handler.ts
- packages/contracts/test/core/dao/dao.ts
- packages/contracts/test/core/permission/permission-manager.ts
- packages/contracts/test/upgrade/dao.ts
This PR fixes some minor typos in the contracts.
Task ID: No task
> fix: typos in contract and comments 

- .github/workflows/subgraph-tests.yml
- packages/subgraph/src/packages/token/utils.ts
Hot Fix: crashing of subgraph on calling none governance token contracts.
> fix: use try_function

- funding.json
We need to add this file because opretro needs to link the project id to the repo so they can also verify that we own the repo.
> docs: Add opRetro project id file

- packages/contracts/src/core/dao/DAO.sol
- packages/contracts/test/core/dao/dao.ts
- packages/contracts/test/core/permission/permission-manager.ts
- packages/contracts/test/framework/dao/dao-factory.ts
- packages/contracts/test/test-utils/uups-upgradeable.ts
> executor interface

- packages/contracts/src/core/dao/DAO.sol
- packages/contracts/src/core/permission/PermissionManager.sol
- packages/contracts/test/core/dao/dao.ts
- packages/contracts/test/core/permission/permission-manager.ts
> some changes

- packages/contracts/src/core/permission/PermissionManager.sol
- packages/contracts/test/core/dao/dao.ts
- packages/contracts/test/core/permission/permission-manager.ts
> condition restrictions

- packages/contracts-ethers/npm/events/DAO.ts
- packages/contracts-ethers/npm/events/DAORegistry.ts
- packages/contracts-ethers/npm/events/PluginRepo.ts
- packages/contracts-ethers/npm/events/PluginRepoRegistry.ts
- packages/contracts-ethers/npm/events/PluginSetupProcessor.ts
- packages/contracts-ethers/npm/structs/DAO.ts
- packages/contracts-ethers/npm/structs/DAOFactory.ts
- packages/contracts-ethers/npm/structs/PluginRepo.ts
- packages/contracts-ethers/npm/structs/PluginSetupProcessor.ts
- packages/contracts-ethers/npm/structs/index.ts
> fix broken imports in osx-ethers

- packages/artifacts/package.json
> remove prepublishOnly

- packages/contracts/deploy/update/to_v1.4.0/01_Info.ts
- packages/contracts/hardhat.config.ts
> ci: Update hardhat configs

- packages/contracts/hardhat-zksync.config.ts
> ci: Update zksync configs

- packages/contracts/networks.ts
> add linea and mode
